Add aggregate function to SeriesString: to_json_array
objectiv/objectiv-analytics pull request #1062
Opened 2022-07-21 14:18 UTC by thijs-obj

2022-07-21 14:20 UTC, thijs-obj commented on bach/bach/series/series_string.py
> +        # change the sorting. If order_by was not deterministic, then this will make it deterministic.
We could probably use this trick in other places too, to get rid of non-determinism

2022-07-21 14:37 UTC, thijs-obj commented on bach/bach/series/series_string.py
> +    def to_json_array(self, partition: WrappedPartition = None) -> 'SeriesJson':
Not 100% sure about the name, was also thinking about things like `aggregate_to_json_array`

2022-07-21 14:38 UTC, thijs-obj commented on bach/bach/series/series_string.py
> +    def to_json_array(self, partition: WrappedPartition = None) -> 'SeriesJson':
Support the partition parameter here, as we also seem to do that for other aggregation functions

2022-07-21 14:38 UTC, thijs-obj commented on bach/bach/series/series_string.py
> +        BigQuery does not support 'asc nulls last' inside aggregations. So we sort 'asc nulls first'.
This is quite unfortunate, but didn't know a work-around

2022-07-22 08:50 UTC, vard-obj commented on bach/tests/functional/bach/test_series_string.py
> +    print(series_json_array.view_sql())
guess the `print` is not needed.

2022-07-22 08:51 UTC, vard-obj approved these changes
Left minor comments, LGTM.

2022-07-24 18:29 UTC, KathiaBarahona requested changes
As I mentioned in the comments, this functionality is a window function in a nutshell. It seems to me there might be some code duplication, and all this can be handled by Window class (as we do for the rest of window functions)

2022-07-24 18:29 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +        Aggregate function: Concatenate the values of this Series into a json array
IMHO `Concatenate` can get mixed up with "concatenating" arrays.
```suggestion
        Aggregate function: Group the values of this Series into a json array
```

2022-07-24 18:29 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +        this Series does not have a deterministic sorting, then the values are sorted by the values
**question** Shouldn't we also allow the user to decide if the values should be in ascending or descending order?

2022-07-24 18:29 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +        this Series does not have a deterministic sorting, then the values are sorted by the values
Also I think the following sentence is a bit confusing ``If
        this Series does not have a deterministic sorting, then the values are sorted by the values themselves.``

2022-07-24 18:29 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +        BigQuery does not support 'asc nulls last' inside aggregations. So we sort 'asc nulls first'.
mm can we a single function that does this and maybe just add a parameter if `nulls last` statement should be added? I mean we already have this function in `DataFrame` and `Window` class. Much be easier for maintainability.

2022-07-24 18:29 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +    def to_json_array(self, partition: WrappedPartition = None) -> 'SeriesJson':
Based on BigQuery's documentation, this is actually a window function. IMO, naming should be `window_array_agg`. Documentation can help telling user this actually returns a json series.

2022-07-24 18:29 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +    def to_json_array(self, partition: WrappedPartition = None) -> 'SeriesJson':
Also, we should add a check to know if the partition is correct.
```suggestion
    def to_json_array(self, window: Optional[WrappedWindow] = None) -> 'SeriesJson':
```

2022-07-25 09:13 UTC, thijs-obj commented on bach/tests/functional/bach/test_series_string.py
> +    print(series_json_array.view_sql())
good one. I was a bit sloppy in looking over this before submitting, my bad.
```suggestion
```

2022-07-25 09:13 UTC, thijs-obj commented on bach/tests/functional/bach/test_series_string.py
> +    series_city = df['city']
```suggestion
```

2022-07-25 09:16 UTC, thijs-obj commented on bach/bach/series/series_string.py
> +        this Series does not have a deterministic sorting, then the values are sorted by the values
> **question** Shouldn't we also allow the user to decide if the values should be in ascending or descending order?

The user can decide whether the sorting is ascending/descending. For example to get the values sorted descending one can simply do: 
```python
series_object.sort_values(ascending=False).to_json_array()
```

2022-07-25 09:18 UTC, thijs-obj commented on bach/bach/series/series_string.py
> +        this Series does not have a deterministic sorting, then the values are sorted by the values
> Also I think the following sentence is a bit confusing `If this Series does not have a deterministic sorting, then the values are sorted by the values themselves.`

I am going to change this to
`If this Series does not have a deterministic sorting, then the values are additionally sorted by the values themselves.`
i.e. add an 'additionally' in there. Does that clarify things? An alternative could be just leaving this sentence out completely. Or do you have another textual suggestion?

2022-07-25 09:22 UTC, thijs-obj commented on bach/bach/series/series_string.py
> +    def to_json_array(self, partition: WrappedPartition = None) -> 'SeriesJson':
I don't think BigQuery considers this a window function, it is listed under "Aggregate functions": https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#array_agg

Same for Postgres: https://www.postgresql.org/docs/14/functions-aggregate.html

2022-07-25 09:53 UTC, thijs-obj commented on bach/bach/series/series_string.py
> +    def to_json_array(self, partition: WrappedPartition = None) -> 'SeriesJson':
Undid this change again, as I don't think this is a Window function. See other comment

2022-07-25 19:19 UTC, thijs-obj commented on bach/bach/series/series_string.py
> +        BigQuery does not support 'asc nulls last' inside aggregations. So we sort 'asc nulls first'.
I created a separate PR that unites this function with the one in `Window`. I didn't include the one in `DataFrame` in that PR because there are some more differences between those, e.g. in the checks that DataFrame does.

https://github.com/objectiv/objectiv-analytics/pull/1070

2022-07-25 19:26 UTC, thijs-obj commented on bach/tests/functional/bach/test_series_string.py
> +def test_to_json_array_sorting_null(engine):
Completely changed this test since the first review round to also include `None` values

2022-07-26 12:17 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +    def to_json_array(self, partition: WrappedPartition = None) -> 'SeriesJson':
ah wait, I think I misunderstood the expression you are using.  As in the docs it seems its possible to define a window specification.

2022-07-26 12:18 UTC, KathiaBarahona approved these changes

2022-07-26 12:52 UTC, merged