Bach - extracted order_by_expression function
objectiv/objectiv-analytics pull request #1070
Opened 2022-07-25 19:17 UTC by thijs-obj

Based on review comment https://github.com/objectiv/objectiv-analytics/pull/1062#discussion_r928295212

2022-07-25 19:23 UTC, thijs-obj commented on bach/tests/unit/bach/test_series_window_functions.py
> +        assert result_sql == 'row_number() over ( order by `b` asc nulls first )'
I think this actually changes behaviour of the window functions. Not sure if it's an improvement, but I do think that adding  things like 'nulls first' guarantees consistenty between BigQuery and Postgres, and that might not have been consistent before? :thinking:

2022-07-26 12:15 UTC, KathiaBarahona commented on bach/tests/unit/bach/test_series_window_functions.py
> +        assert result_sql == 'row_number() over ( order by `b` asc nulls first )'
maybe adding a test comparing both behaviors? I think this change might introduce changes in modelhub without knowing

2022-07-26 12:15 UTC, KathiaBarahona approved these changes
lgtm, tho I'm not sure if `get_order_by_expression` should be in partitioning module.

2022-07-26 13:20 UTC, thijs-obj commented
> lgtm, tho I'm not sure if `get_order_by_expression` should be in partitioning module.

It's used by a window functions and an aggregate function, so this seemed like an okayish place to put it. Do you have a concrete proposal that you think is better?

2022-07-26 13:26 UTC, thijs-obj commented on bach/tests/unit/bach/test_series_window_functions.py
> +        assert result_sql == 'row_number() over ( order by `b` asc nulls first )'
I think having some tests is a good idea. But adding tests with nulls for all window functions is a quite a bit of work. The reason for this PR is to make maintainability [easier](https://github.com/objectiv/objectiv-analytics/pull/1062#discussion_r928295212), but I am not sure if that goal justifies me spending more time on this issue now to add a load of tests. So I propose that we then create a separate issue for this PR, and plan that in weekly planning. What do you think about that?

2022-08-01 08:23 UTC, KathiaBarahona commented on bach/bach/partitioning.py
> +        desc_expr = Expression.construct('desc nulls last')
```suggestion
        desc_expr = Expression.construct('desc nulls first')
```

2022-08-01 08:23 UTC, KathiaBarahona requested changes
desc + nulls first is wrong

2022-08-01 09:58 UTC, thijs-obj commented
> desc + nulls first is wrong

What do you mean by wrong? Is this different from what Pandas does, or how we did it in the past, or ... ?

2022-08-01 10:02 UTC, KathiaBarahona commented
> > desc + nulls first is wrong
> 
> What do you mean by wrong? Is this different from what Pandas does, or how we did it in the past, or ... ?

( I'm dumb, was replying on your comment)

See https://github.com/objectiv/objectiv-analytics/pull/1070#discussion_r934263974

when `nulls_last is False` and `order_by.asc is False`, the final expression in the order by clause is setting `ORDER BY COLUMN desc nulls last`

2022-08-01 12:00 UTC, thijs-obj commented
> > > desc + nulls first is wrong
> > 
> > 
> > What do you mean by wrong? Is this different from what Pandas does, or how we did it in the past, or ... ?
> 
> ( I'm dumb, was replying on your comment)
> 
> See [#1070 (comment)](https://github.com/objectiv/objectiv-analytics/pull/1070#discussion_r934263974)
> 
> when `nulls_last is False` and `order_by.asc is False`, the final expression in the order by clause is setting `ORDER BY COLUMN desc nulls last`
> 
> is yielding the same expression when having `nulls_last is True` and `order_by.asc is False`

Let's discuss tomorrow after stand-up. I am not quite following what you mean. To me it looks like the behaviour of the function matches what the docstring says it does, and the test for SeriesString keeps working. I agree that this might change things for window functions, but I believe your PR fixes that?

2022-08-11 12:37 UTC, thijs-obj commented
Closing this PR. PR https://github.com/objectiv/objectiv-analytics/pull/1089 contains all commits in this branch, with a lot more refinement added

2022-08-11 12:37 UTC, closed without merging