Fa discovery
objectiv/objectiv-analytics pull request #1103
Opened 2022-08-03 12:52 UTC by vard-obj

2022-08-04 08:17 UTC, KathiaBarahona commented on modelhub/modelhub/modelhub.py
> +        model.
Not really, function is not receiving any param
```suggestion
```

2022-08-04 08:22 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        if self.groupby is not None and self.groupby is not not_set:
not really, for example:

```
df_steps = FunnelDiscovery().get_navigation_paths(..., by='user_id')

# new FunnelDiscovery instance with empty groupby
filtered_df_steps = FunnelDiscovery().filter_navigation_paths_to_conversion(df_steps, ...)
```

2022-08-04 08:24 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +                                              ) -> bach.DataFrame:
```suggestion
    def filter_navigation_paths_to_conversion(
        self, 
        steps_df: bach.DataFrame,
        conversion_events_df: bach.DataFrame,
        conversion_location_column: str = 'feature_nice_name'
    ) -> bach.DataFrame:
```

2022-08-04 08:25 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        :returns: bach DataFrame, filtered each row of steps_df to the
:P probably this is missing some words

2022-08-04 08:27 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +            )
mmm let's avoid calling private methods, probably `_check_groupby` should be a public method in `modelhub.utils`

2022-08-04 08:28 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        self.groupby = by
I don't think you actually need `self.groupby`

2022-08-04 08:28 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        if self.groupby is not None and self.groupby is not not_set:
```suggestion
        if by is not None and by is not not_set:
```

2022-08-04 08:30 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +            return step_df[step_series.name]
This should be a `staticmethod` in `FunnelDiscovery` class

2022-08-04 08:33 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        _steps_df['_index'] = steps_df.groupby().window().location_stack_step_1.window_row_number()
I will be carefull with this line, what if the location stack event has actually a different name?
```suggestion
        _steps_df['_index'] = steps_df.groupby().window().location_stack_step_1.window_row_number()
```

2022-08-04 08:35 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        _steps_df = _steps_df.reset_index().set_index(index_columns)
This is going to break if `_index` is not part of the `_steps_df`. I think you can know how was  `steps_df` grouped based on the series in the index

2022-08-04 08:39 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +    def filter_navigation_paths_to_conversion(self, steps_df, conversion_events_df,
**suggestion** Maybe this function can be separated into other methods, as it's a bit complex and hard to handle

2022-08-04 08:41 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +         after encountering the first conversion location step.
Maybe a bit more explanation about the steps will be good, as its not clear what the function actually does

2022-08-04 08:44 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        Filter steps dataframe rows to first conversion location.
Maybe?
```suggestion
        Identify the first conversion step per each navigation path.
```

2022-08-04 08:44 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        :param steps_df: dataframe which one gets from `get_navigation_paths` method output.
:P maybe some reference to the method, for docs

2022-08-04 08:46 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        :param steps_counter_df: constructing pandas links dataframe out of steps_counter_df.
not sure if I understand this :thinking:

2022-08-04 08:49 UTC, KathiaBarahona requested changes
left some comments, I haven't take a look to the notebook. It's better to have a separate PR just for it. Because maybe some of this methods can be private and just provide the params to the sankey diagram :thinking: . But have to see more how they are been used.

2022-08-04 12:39 UTC, vard-obj commented on modelhub/modelhub/models/funnel_discovery.py
> +            )
Good idea, will create a separate PR.

2022-08-05 08:16 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +    """
missing docstring:)

2022-08-05 08:30 UTC, KathiaBarahona reviewed
Left a couple of comments. I think my major concern is that most of this functions expect a dataframe with certain structure but its not quite clear which are the steps to follow for generating such df.

Also, I didn't went through deeply to `plot_sankey_diagram`, is it necessary to use pandas?

2022-08-05 08:30 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        pass
```suggestion
```

2022-08-05 08:30 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        @param step_series: series of ith step:
```suggestion
        :param step_series: series of ith step:
```

2022-08-05 08:30 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +    def tag_step(step_series: bach.Series) -> bach.Series:
let's make this private
```suggestion
    def _tag_step(step_series: bach.Series) -> bach.Series:
```

2022-08-05 08:30 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +    def melt_steps(self, steps_df: bach.DataFrame) -> bach.Series:
same here 
```suggestion
    def _melt_steps(self, steps_df: bach.DataFrame) -> bach.Series:
```

2022-08-05 08:30 UTC, KathiaBarahona commented on modelhub/modelhub/models/funnel_discovery.py
> +        result_df = steps_df[steps_df[conv_step_num_column] != 1]
what if `conv_step_num_column` does not exist in `steps_df`?

2022-08-05 13:28 UTC, closed without merging