Support SeriesJson on Athena
objectiv/objectiv-analytics pull request #1138
Opened 2022-08-10 13:56 UTC by thijs-obj

Changes:
* Enable all tests in `test_series_json.py` for Athena
* Implemented functionality in `SeriesJson`
* Added Athena specific subclass of `JsonAccessor`
* Added Athena specific subclass of `ArrayFlattening`

2022-08-10 18:34 UTC, KathiaBarahona commented on bach/bach/series/series_json.py
> +            fmt_str = f'{{}} {comparator} {{}}'
**question** Is this block on purpose? We do the same for BQ

2022-08-10 18:37 UTC, KathiaBarahona commented on bach/bach/series/series_json.py
> +    supported_value_types = (dict, list, str, float, int, bool)
**question** If we support those new types, why not supporting the casting of the `dtypes`?

2022-08-10 18:39 UTC, KathiaBarahona commented on bach/bach/series/series_json.py
> +            "slice(cast({} as array(json)), {}, {})",
nice that we don't need to simulate it :rocket:

2022-08-10 18:42 UTC, KathiaBarahona commented on bach/bach/series/series_json.py
> +            return Expression.construct(f'({{}} {value} + 1)', array_len)
**question** Maybe making a helper function for both BQ and Athena? The differences are not that big

2022-08-10 18:45 UTC, KathiaBarahona commented on bach/bach/series/series_json.py
> +            raise TypeError(f'Values in the key dict, should all be strings')
We should add these validations for both BQ and PG. IMHO is better to have the same behavior for all engines

2022-08-10 18:46 UTC, KathiaBarahona commented on bach/bach/series/series_json.py
> +        else:
**nit-pick** this `else` block is not necessary since `if` block has a return statement

2022-08-11 06:31 UTC, thijs-obj commented
Added small fix for test that I initially forgot in 2e208b1918caf72bca83f23ad86d60f555a9e91f. Will have a look at the review comments in a bit

2022-08-11 09:38 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_json.py
> +    if is_postgres(engine) or is_athena(engine):
**nit-pick** Need to update comment in line 231

2022-08-11 10:17 UTC, KathiaBarahona commented on bach/bach/series/series_json.py
> +            .copy_override_type(SeriesString)
Did some tests here and seems there are a couple of inconsistencies between all engines:

```
def test_json_get_item_to_pandas_inconsistencies(engine, dtype):
    import pandas as pd
    import json
    pdf = pd.DataFrame(
        {
            'test_column': [
                json.dumps({'a': '"b"', 'b': 1, 'c': [0, 1, 2]}),
                json.dumps({}),
                json.dumps({'c': [3, 4, 5]})
            ]
        }
    )

    df = DataFrame.from_pandas(engine, df=pdf, convert_objects=True)
    df['test_column'] = df['test_column'].astype('json')
    df['example_1'] = df['test_column'].json.get_value('a')
    df['example_2'] = df['test_column'].json.get_value('a', as_str=True)
    df['example_3'] = df['test_column'].json.get_value('b')
    df['example_4'] = df['test_column'].json.get_value('b', as_str=True)
    df['example_5'] = df['test_column'].json.get_value('c')
    df['example_6'] = df['test_column'].json.get_value('c', as_str=True)

    example_cols = [f'example_{i}' for i in range(1, 7)]
    assert_equals_data(
        df[example_cols],
        expected_columns=['_index_0'] + example_cols,
        expected_data=[
            [0, '"b"',  '"b"',    1,  '1', [0, 1, 2], '[0, 1, 2]'],
            [1,  None,   None, None, None,      None,        None],
            [2,  None,   None, None, None, [3, 4, 5], '[3, 4, 5]'],
        ]
    )
```

The test from above passes for PG and failed for both BQ and Athena.

I guess for BQ is kinda expected because of the use of strings instead of jsons. But seems that with Athena is when getting value as str. Tried experimenting a bit with `json_extract_scalar` but does not work with arrays, so returns NULL in that case. Also, when stringifying an array, the final format is different from PG

2022-08-11 10:36 UTC, KathiaBarahona commented on bach/bach/series/series_json.py
> +            .copy_override(expression=expression)
FYI, for both BQ and Athena, array lengths of "non array" objects, is None. PG will raise an error

2022-08-11 11:22 UTC, KathiaBarahona commented on bach/bach/series/series_json.py
> +    def _find_in_json_list(self, filtering_slice: Dict[str, str], is_start: bool):
Failing for Athena:

```pytest
def test_json_dict_slicing_failing(engine, dtype):
    import pandas as pd
    import json
    pdf = pd.DataFrame(
        {
            'test_column': [
                json.dumps({'a': '"b"', 'b': 1, 'c': [0, 1, 2]}),
                json.dumps({}),
                json.dumps({'c': [3, {'a': '1'}, 4, 5, 6]})
            ]
        }
    )

    df = DataFrame.from_pandas(engine, df=pdf, convert_objects=True)
    df['test_column'] = df['test_column'].astype('json')
    df['example_1'] = df['test_column'].json.get_value('c')
    df['example_2'] = df['example_1'].json[{'a': '1'} : 3]

    assert_equals_data(
        df[['example_1', 'example_2']],
        expected_columns=['_index_0', 'example_1', 'example_2'],
        expected_data=[
            [0, [0, 1, 2], []],
            [1,  None, []],
            [2, [3, {'a': '1'}, 4, 5, 6], [{'a': '1'}, 4]],
        ],
        use_to_pandas=True,
    )

```

2022-08-11 11:37 UTC, KathiaBarahona commented on bach/bach/series/series_json.py
> +            .copy_override_type(SeriesString)
**update** forgot to add `use_to_pandas=True`. Results for both BQ and Athena are actually the same for this test, but the result from `example_3` and `example_6` are different from PG.

2022-08-11 11:39 UTC, KathiaBarahona requested changes
Went thoroughly each implementation and most are working as expected. Though in some scenarios results differ from engines, also it seems slicing using a dict is not working. Left a couple of tests to show this points

2022-08-11 14:47 UTC, thijs-obj commented on bach/bach/series/series_json.py
> +    def _find_in_json_list(self, filtering_slice: Dict[str, str], is_start: bool):
I think the issue here is that part of the sql we generate is this:
```sql 
cast(json_extract(json_parse("test_column"), '$["c"]') as array(map(varchar, json)))
```
And that gives an error as `[3, {'a': '1'}, 4, 5, 6]` cannot be converted to `array(map(varchar, json))`. It doesn't kill the query as it is wrapped in a `try()`, so it just gives `null`.

Might be fixable by casting to just `array(json)`, and then in the filter method cast each item separately to `map(varchar, json)`  :thinking:

2022-08-11 14:53 UTC, thijs-obj commented on bach/bach/series/series_json.py
> +    def _find_in_json_list(self, filtering_slice: Dict[str, str], is_start: bool):
Created this issue to track this: https://github.com/objectiv/objectiv-analytics/issues/1141

2022-08-11 15:00 UTC, thijs-obj commented on bach/bach/series/series_json.py
> +            return Expression.construct(f'({{}} {value} + 1)', array_len)
Considered that, but as the functions were slightly different it seemed easier to just have two different functions for now. When we have many similar functions in the future we can always merge them

2022-08-11 15:03 UTC, thijs-obj commented on bach/bach/series/series_json.py
> +    supported_value_types = (dict, list, str, float, int, bool)
This is not about what we can cast from, but what `supported_value_types()` supports. And since we just do `json.dumps` there, we actually already supported these values. 

Made this change at some point cause I thought I needed to use `supported_value_to_literal`, later changed the part where I used that, but kept this change as it was in fact correct

2022-08-11 15:17 UTC, thijs-obj commented on bach/bach/series/series_json.py
> +            fmt_str = f'{{}} {comparator} {{}}'
This was wrong. Changed in e2d7ea83f81c6c6abfeb97895a08d255853718ca to only support comparisons between `json` left and `json` right, and added https://github.com/objectiv/objectiv-analytics/issues/1142 to fix this consistently in the future

2022-08-11 15:18 UTC, thijs-obj commented on bach/bach/series/series_json.py
> +        else:
Changed in e2d7ea83f81c6c6abfeb97895a08d255853718ca

2022-08-15 07:34 UTC, KathiaBarahona approved these changes

2022-08-15 07:48 UTC, merged