Bach[Athena]: Support string functions for Athena
objectiv/objectiv-analytics pull request #1189
Opened 2022-08-30 07:09 UTC by KathiaBarahona

- Missing `get_dummies` TBD. Problem with column naming, since Athena does not support upper case in column names.
- Missing `to_json_array`

Refactored `str.__get_item__` , since `athena` does not support `left` and `right` functions.

2022-08-30 07:12 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_string.py
> +        slice(0, None), slice(1, None), slice(5, None), slice(-5, None), slice(-1, None),
Seems this was not testing what it intended (previously `start` attr from the slice was None and `stop` attr actually had the value)

2022-08-30 07:13 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_string.py
> +            _slice_2 = slice(s, s + 1)
there was a bug here, seems `str[s]` was not working in a pythonic way...

2022-08-30 07:29 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +        if stop is None or stop == -1:
need to actually test `-1`

2022-08-30 07:30 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_string.py
> +        slice(0, None), slice(1, None), slice(5, None), slice(-5, None), slice(-1, None),
:thinking: will add both cases

2022-08-30 08:43 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +        if stop is None or stop == -1:
fixed here https://github.com/objectiv/objectiv-analytics/pull/1189/commits/e8b2767249a37d7b0e42abb77f0b9bba598c626c

2022-08-30 08:43 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_string.py
> +        slice(0, None), slice(1, None), slice(5, None), slice(-5, None), slice(-1, None),
Added here and also with weird big indexes https://github.com/objectiv/objectiv-analytics/pull/1189/commits/e8b2767249a37d7b0e42abb77f0b9bba598c626c

2022-08-30 12:17 UTC, thijs-obj requested changes
Nice improvement to the string slicing tests, but I think there are still some interesting cases missing. 

I am a big fan of porting the code to use `substr` so we have the same on all database platforms.

2022-08-30 12:17 UTC, thijs-obj commented on bach/bach/series/series_string.py
> +    def _get_substr_expression(self, start=None, stop=None) -> Expression:
Very much appreciate the comments, but still quite hard to review this.

I understand that different databases have slightly different implementations and that leads to some complications. But it's kinda hard to see whether all cases here actually cover all possible inputs.

**Question**: Have you considered not having the separate cases for 3, 4, and 5 and just a sql statement that works for all cases? something like below. This seems much simpler to me, and I don't quite see why it wouldn't work
```python
start_offset_expr = Expression.construct('greatest({}, 0)', start_offset_expr)  # make sure we don't get negative numbers
stop_offset_expr = # something similar to start_offset_expr here
substr_len_expr = Expression.construct('greatest({} - {}, 0)', stop_offset_expr, start_offset_expr)
return Expression.construct('substr({}, {}, {})', base_expr, start_offset_expr, substr_len_expr)
```

2022-09-12 09:26 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +    def _get_substr_expression(self, start=None, stop=None) -> Expression:
`greatest` helped a lot! took me some time, but managed to simplify it a lot. Done in https://github.com/objectiv/objectiv-analytics/pull/1189/commits/1909df24372dfb475d235d65288de43596c01ace

2022-09-12 09:26 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_string.py
> +        slice(None, 3), slice(3, None), slice(None, -3), slice(-3, None),
added https://github.com/objectiv/objectiv-analytics/pull/1189/commits/1909df24372dfb475d235d65288de43596c01ace

2022-09-12 09:27 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +    def len(self) -> 'SeriesInt64':
done here https://github.com/objectiv/objectiv-analytics/pull/1189/commits/1909df24372dfb475d235d65288de43596c01ace

2022-09-12 09:27 UTC, KathiaBarahona commented on bach/bach/series/series_string.py
> +            raise ValueError(f'Type not supported {type(key)}')
https://github.com/objectiv/objectiv-analytics/pull/1189/commits/1909df24372dfb475d235d65288de43596c01ace

2022-09-12 12:36 UTC, thijs-obj commented on bach/bach/series/series_string.py
> +    def _get_substr_expression(self, start=None, stop=None) -> Expression:
cool! much easier to read now :+1:

2022-09-12 12:36 UTC, thijs-obj approved these changes
lgtm

2022-09-15 07:46 UTC, merged