Bach: make ffill propagation on windows possible
objectiv/objectiv-analytics pull request #1360
Opened 2022-10-14 12:05 UTC by hendrik-obj

- [ ] make ffill method possible on df with window
- [ ] fix materialization of fillna with method ffill/bfill

2022-10-14 13:18 UTC, vard-obj commented on bach/tests/functional/bach/test_df_fillna.py
> +    pdf = pdf.reset_index(names='_index_0').sort_values('_index_0')
Shall we change it to this?
```suggestion
    pdf = pdf.reset_index().rename(columns={'index': '_index_0'})
```

2022-10-20 08:54 UTC, hendrik-obj commented on bach/bach/operations/value_propagation.py
> +        return df[self._df.data_columns].materialize(node_name='nafilled')
This is done so you can select from the data frame later. See the test that is added:
```
fillna_check_ffill_expected[fillna_check_ffill_expected.F=='f']
```

2022-10-21 08:50 UTC, KathiaBarahona commented on bach/bach/operations/value_propagation.py
> +        window_group: Optional[Union[str, Sequence[str]]] = None
**suggestion** Maybe providing a `WrappedWindow` instead? this is how we normally apply window functions

2022-10-21 08:54 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_df_fillna.py
> +    df_ffill = vp.propagate(window_group='groups')
shouldn't it be the same format as pandas? This means we need to expose `ValuePropagation` in bach's API.

2022-10-21 09:22 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_df_fillna.py
> +    )
I think it's not necessary to test this, else we will be doing 2 query executions and might take some time for Athena and BQ
```suggestion
```

2022-10-21 09:26 UTC, KathiaBarahona commented on bach/bach/operations/value_propagation.py
> +        df = self._add_partition_per_data_columns(df, window_group=window_group)
Can't comment on the line, but seems to me we should check if `df` already has a groupby in line 73. Seems to me it will break otherwise

2022-10-21 10:00 UTC, KathiaBarahona requested changes
As I mentioned in other comment. I think that the correct format if we want to apply propagation is grouping by the df first and later call fillna (pandas syntax). (`df.groupby(by='x').fillna(method='ffill')`)

I think a way to do this is just extracting the index columns from the df and use that as `window_group` instead:
``` python
    def __init__(self, df: DataFrame, method: str):
        self._df = df
        self._method = ValuePropagationMethod.get_method(method)
        
    def propagate(
        self,
        sort_by: Optional[Union[str, Sequence[str]]] = None,
        ascending: Union[bool, List[bool]] = True,
    ):
        df = self._df.copy()

        gb = []
        if df.group_by:
            gb = list(df.group_by.index.keys())
            df = df.copy_override(
                series={s.name: s.copy_override(group_by=None) for s in df.data.values()},
                group_by=None,
            )
        if sort_by:
            df = df.sort_values(by=gb + sort_by, ascending=ascending)
        elif gb:
            df = df.sort_values(by=gb, ascending=ascending)
        elif not df.order_by:
            raise Exception('dataframe must be sorted in order to apply forward or backward fill.')

        # Number each sorted row this way we avoid issues when sorting NULL values
        # since bfill is ffill with reversed sort (this might generate different results)
        base_series = df[df.data_columns[0]]
        # order nulls last in window function, else numbering will be wrong
        window = df.groupby(by=gb).window(na_position='last')
        df[self.ROW_NUMBER_SERIES_NAME] = base_series.window_row_number(window)
        df = df.materialize(node_name='numbered_fillna')

        # sort values by group_by indexes and row number
        by = gb + [self.ROW_NUMBER_SERIES_NAME]
        ascending = self._method == ValuePropagationMethod.FORWARD_FILL

        df = df.sort_values(by=by, ascending=ascending)
        df = self._add_partition_per_data_columns(df, window_group=gb)

        # sorting is lost due to materialization, still requires it
        df = df.sort_values(by=by, ascending=ascending)
        df = self._propagate_first_value_per_partition(df, window_group=gb)

        # sort values, this way we respect the provided order by
        df = df.sort_values(by=by)
        return df[self._df.data_columns].materialize(node_name='nafilled')
```

Current implementation breaks if the df is already grouped, so I think its better to fix that now since this PR intends to consider the groupby anyways

2022-10-21 10:02 UTC, KathiaBarahona commented on bach/bach/operations/value_propagation.py
> +        window_group: Optional[Union[str, Sequence[str]]] = None
nvm, I think this param is better to be removed. I explain why in another comment

2022-10-28 14:56 UTC, hendrik-obj commented
ok so now I implemented a groupby parameter to ffill/bfill. Couldn't mimic the regular pandas syntax (df.groupby('some_column').ffill()) without big modifications to core Bach, as df.groupby('some_column') doesn't have the same index as df (which would be needed for the correct output of ffill with groups). 

Therefore this pr is back to draft, let's discuss.

2022-11-01 11:57 UTC, KathiaBarahona approved these changes
had to approve my own changes as I cannot unblock the PR

2022-11-01 13:54 UTC, hendrik-obj reviewed
changes are good for me. more generic approach providing a `WrappedPartition`

2022-11-01 14:27 UTC, vard-obj approved these changes
LGTM

2022-11-01 14:28 UTC, merged