Funnel conversion
objectiv/objectiv-analytics pull request #1366
Opened 2022-10-17 09:53 UTC by vard-obj

2022-10-17 15:41 UTC, hendrik-obj requested changes
I think there can be some optimizations here and there, but left two main comments about functionality. If those are addressed, and the docs are clear on how to use this function, the results look good.

2022-10-17 15:41 UTC, hendrik-obj commented on modelhub/modelhub/aggregate.py
> +                          groupby: Union[List[Union[str, Series]], str, Series] = 'user_id',
not sure if we should now support anything other that user_id (also below there is some user_id hardcoded in the function)

2022-10-17 16:04 UTC, hendrik-obj commented on modelhub/modelhub/aggregate.py
> +        df_root_user = data.drop_duplicates(subset=[location, 'user_id'], keep='first')
should be sorted by session_id and session_hit_number

2022-10-18 10:40 UTC, hendrik-obj commented on modelhub/modelhub/aggregate.py
> +        return result[columns]
sort descending by users that entered each step

2022-10-18 12:12 UTC, hendrik-obj commented on modelhub/modelhub/aggregate.py
> +        result['dropoff'] = result['dropoff'].fillna(0)
'drop-off' can be calculated as 'n_users' - 'n_users_completed_step'. Then 'drop-off' can be divided by the 'n_users_start'. If we do that, drop_off_locations and therefore this merge is not necessary anymore.

2022-10-18 15:18 UTC, hendrik-obj reviewed
functionally all good. Some small comments regarding names and docs. Tests should pass. Then good

2022-10-18 15:18 UTC, hendrik-obj commented on modelhub/modelhub/aggregate.py
> +                          location_stack: LocationStackType = None) -> bach.DataFrame:
shall we call it `funnel_steps_column`, or something like that, a column that can be a SeriesLocationStack or SeriesString (but `funnel_steps_column` itself can also be just a `str`)?

Also maybe we should not accept `None` for this function, as I think it does not make a lot of sense in most cases.

2022-10-18 15:18 UTC, hendrik-obj commented on modelhub/modelhub/aggregate.py
> +        N.B. Filter the dataframe beforehand if you don't want to include all location stacks .
```suggestion
        N.B. Filter the dataframe beforehand to filter down to the funnel locations.
```

2022-10-18 15:18 UTC, hendrik-obj commented on modelhub/modelhub/aggregate.py
> +        df_root_user = data.sort_values(['session_id', 'session_hit_number']).\
can we use `check_objectiv_dataframe` or the decorator to check if all columns that are needed for this function are in `data`?

2022-10-19 07:37 UTC, ivarpruijn commented on modelhub/modelhub/aggregate.py
> +        is based on events on each location stack.
Does it make sense to include this here?

2022-10-19 07:37 UTC, ivarpruijn commented on modelhub/modelhub/aggregate.py
> +            `dropoff_share` (fraction of the users dropping out at the given step).
Think this should be updated

2022-10-19 09:23 UTC, vard-obj commented on modelhub/modelhub/aggregate.py
> +                          location_stack: LocationStackType = None) -> bach.DataFrame:
If the value is None it takes the `feature_nice_name`. I kind of followed the 'standard', as we have the same parameter name in the `drop_off_locations`. In that case, shall we change the parameter name in both functions?

2022-10-19 09:44 UTC, merged