Bach: Add Series.unique() and Series[slice]
objectiv/objectiv-analytics pull request #274
Opened 2021-11-09 14:27 UTC by jansentom

giving us:
```
# get the unique values
bt.municipality.unique().head()

# slice the first three 
first_muni = bt.municipality[:3] 

# or the first three unique ones
first_unique_muni = bt.municipality.unique()[:3]
```

Update: removed value counts from this MR, as it had quite some work to be done and unique() is ready

2021-11-10 08:40 UTC, jansentom commented on bach/bach/series/series.py
> +            value_counts = self.window_ntile(
This kinda combines everything we've built. Pretty neat.

2021-11-10 09:43 UTC, thijs-obj commented on bach/bach/partitioning.py
> +        if not isinstance(order_by, list) or not all(isinstance(ob, SortColumn) for ob in order_by):
Is this just a precaution, or something that actually went wrong in some instance? If the latter, then when should perhaps have the same check in DataFrame

2021-11-10 13:30 UTC, jansentom commented on bach/bach/partitioning.py
> +        if not isinstance(order_by, list) or not all(isinstance(ob, SortColumn) for ob in order_by):
I made a mistake in value_counts() that took me a while to figure out. Could have also run mypy probably

2021-11-10 13:49 UTC, thijs-obj requested changes
I think we need to make some improvements to the docstring and tests and/or have sorting by default

2021-11-10 13:49 UTC, thijs-obj commented on bach/bach/series/series.py
> +        :param bins: Rather than count values, group them into half-open bins.
We should mention here that this binning is different from pandas. I think it's better than pandas, but people might disagree :)

It seems pandas takes the min and max of the series, and then creates the specified number of buckets with each bucket covering a similarly wide range of values regardless of how many values will end up in each bucket. Whereas we create buckets with the same number of values in each bucket.

Example:
values: `1, 2, 3, 4, 5, 10`
number of bins: 2

pandas result: bucket one (range 1 to 5): `1, 2, 3, 4, 5` and  bucket two (range 6 to 10): `10`
our result: bucket one (lowest three values): `1, 2, 3` and bucket two (highest three values): `4, 5, 10`

2021-11-10 13:49 UTC, thijs-obj commented on bach/bach/series/series.py
> +        :param bins: Rather than count values, group them into half-open bins.
This also explains why pandas has the `normalize` parameter: one bucket might contain much more values than the next. Whereas in our case the normalized values will be pretty useless, e.g. if there are `N` items and `X` buckets and `N` is a multiple of `X` then the normalized value is always `N/X` in our implementation and if `N` is not a multiple of `X` then it is close to that value.

2021-11-10 13:49 UTC, thijs-obj commented on bach/bach/series/series.py
> +        :param bins: Rather than count values, group them into half-open bins.
perhaps we should check with @hendrik-obj what to do with this

2021-11-10 13:49 UTC, thijs-obj commented on bach/bach/series/series.py
> +            value_counts = self.window_ntile(
This is pretty neat indeed

2021-11-10 13:49 UTC, thijs-obj commented on bach/tests/functional/bach/test_series.py
> +def test_positional_slicing():
Below I wrote a comment that a test relies on a certain data-ordering which is not guaranteed by the database, same goes for this test. There is no order by clause in the generated sql

2021-11-10 13:52 UTC, jansentom commented on bach/bach/series/series.py
> +        if partition:
yes, and we later might support it. It's possible, but a lot of work (because we have to stack group_by's)

2021-11-11 07:57 UTC, jansentom commented on bach/tests/functional/bach/test_series.py
> +    uq = bt.municipality.unique()[:2]
(I actually wrote the above comment yesterday, and did some thinking):
We need a solution for ordering that is multi-column, even for a single series. I've added a comment in the docstring for now, and put the ordering on the TODO list)

2021-11-17 18:52 UTC, jansentom commented
I've removed value_counts(), as there was too much discussion on it. Merging the rest.

2021-11-17 18:53 UTC, merged