wip: Models hub
objectiv/objectiv-analytics pull request #329
Opened 2021-12-10 15:28 UTC by hendrik-obj

2021-12-15 10:23 UTC, jansentom requested changes
Pretty cool stuff. I left some comments of which some really need attention, but should not be a lot of work.

2021-12-15 10:23 UTC, jansentom commented on analysis/bach_open_taxonomy/bach_open_taxonomy/series/series_objectiv.py
> +        def conversions(self, name, partition='session_id'):
I really think this and previous method need good docstrings before we ship. This is quite crucial, as we want to show how simple to use everything is. Personally, I find this method really hard to understand, but I tried to review anyway.

2021-12-15 10:23 UTC, jansentom commented on analysis/bach_open_taxonomy/bach_open_taxonomy/series/series_objectiv.py
> +            df = df.materialize()
this should not be required as `conversion()` only adds simple expressions?

2021-12-15 10:23 UTC, jansentom commented on analysis/bach_open_taxonomy/bach_open_taxonomy/series/series_objectiv.py
> +            df = df.materialize()
Duplicate, this one can go.

2021-12-15 10:23 UTC, jansentom commented on analysis/bach_open_taxonomy/bach_open_taxonomy/series/series_objectiv.py
> +            exp = f"count({{}}) over (partition by {{}} order by {{}}, {{}})"
This one is supported by Bach directly:
`df['_conversion_counter'].count(df.groupby('_conversion_counter').sort_values([partition, 'moment']).window())` of the top of my head.

2021-12-15 10:23 UTC, jansentom commented on analysis/bach_open_taxonomy/bach_open_taxonomy/series/series_objectiv.py
> +        sample_df.start_date = start_date
where do these come from? For me this is broken.

2021-12-15 10:23 UTC, jansentom commented on analysis/bach_open_taxonomy/bach_open_taxonomy/stack/util.py
> +def _get_date_range(start_date, end_date):
Shouldn't we move this logic to `DateTimeOperation` aka `.dt`?

2021-12-15 10:23 UTC, jansentom commented on analysis/bach_open_taxonomy/bach_open_taxonomy/series/series_objectiv.py
> +        if engine is None:
Added this to remove some complex looking boilerplate code.

2021-12-15 10:23 UTC, jansentom commented on analysis/notebooks/model-hub-demo-notebook.ipynb
> +    "from bach_open_taxonomy import ObjectivFrame"
@borft @vincenthoogsteder all the sqlalchemy boilerplate here is gone. `from_table` below uses the DSN env variable to establish to connection itself if no engine is given.

2021-12-16 09:28 UTC, vincenthoogsteder commented on analysis/notebooks/model-hub-demo-notebook.ipynb
> +    "from bach_open_taxonomy import ObjectivFrame"
very nice

2021-12-16 13:11 UTC, jansentom approved these changes

2021-12-16 13:12 UTC, merged