implmenenting taxonomy updates into schema
objectiv/objectiv-analytics pull request #330
Opened 2021-12-13 10:32 UTC by vincenthoogsteder

Aligns with this PR:
https://github.com/objectiv/objectiv.io/pull/177

2021-12-13 10:57 UTC, sdirosa commented on schema/base_schema.json5
> +      properties": {
```suggestion
      "properties": {
```

2021-12-13 10:57 UTC, sdirosa commented on schema/base_schema.json5
> +      properties": {
```suggestion
      "properties": {
```

2021-12-13 10:57 UTC, sdirosa commented on schema/base_schema.json5
> +    },
Unrelated, but seems like this contexts went beyond is initial design and is now representing more than just element expanding / collapsing. 

Perhaps we should rename this context to something more appropriate.

2021-12-13 10:57 UTC, sdirosa commented on schema/base_schema.json5
> +    },
I'd add `ApplicationContext` to the required contexts.

This will ensure non interactive Events at least carry for which application are they occurring, even if they have no Location information.

2021-12-13 10:57 UTC, sdirosa commented on schema/base_schema.json5
> +      "requiresContext": ["SectionContext"]
Do we really want to enforce a Section to be present for ApplicationLoaded?

This will prevent SPAs to trigger this event before rendering their UI

2021-12-13 10:57 UTC, sdirosa requested changes
Found a couple of bugs and left some comments

2021-12-13 12:06 UTC, borft commented on schema/base_schema.json5
> +      "requiresContext": [""],
```suggestion
      "requiresContext": [],
```

2021-12-13 12:20 UTC, vincenthoogsteder commented on schema/base_schema.json5
> +      properties": {
sharp fixing

2021-12-13 12:20 UTC, vincenthoogsteder commented on schema/base_schema.json5
> +      properties": {
fixing

2021-12-13 12:21 UTC, vincenthoogsteder commented on schema/base_schema.json5
> +    },
I agree, let's revert this back the description to a more narrow to avoid confusion with overlays

2021-12-13 12:22 UTC, vincenthoogsteder commented on schema/base_schema.json5
> +    },
very good point. Will do, also in the docs

2021-12-13 12:26 UTC, vincenthoogsteder commented on schema/base_schema.json5
> +      "requiresContext": ["SectionContext"]
I agree, it's weird. Esp as NonInteractive events are completely de-coupled from the LocationStack. So let the LS worry about Sections being there, will take it out here.

2021-12-13 12:28 UTC, vincenthoogsteder commented on schema/base_schema.json5
> +      "requiresContext": [""],
sharp, fixing

2021-12-13 12:31 UTC, vincenthoogsteder commented
@sdirosa @borft did an update round based on both your comments

2021-12-13 12:35 UTC, borft commented on schema/base_schema.json5
> +        "referer": {
how does this work for multiple events from different referers in the same request to the collector?

2021-12-13 12:42 UTC, sdirosa commented on schema/base_schema.json5
> +        "referer": {
If I look the backend implementation it looks like the Collector simply fetches the Referer and User-Agent headers and factors an HttpContext out of them, then it enriches all the events in the request with it.

2021-12-13 12:44 UTC, vincenthoogsteder commented on schema/base_schema.json5
> +    },
added this in, then noticed it already has that by inheriting from AbstractEvent, so took it out again

2021-12-13 12:46 UTC, borft commented on schema/base_schema.json5
> +        "referer": {
ah, I see, this was already broken. This actually didn't change at all, it's more the diff that's a bit messy.

2021-12-13 12:48 UTC, borft commented on schema/base_schema.json5
> +      "requiresContext": [""]
```suggestion
      "requiresContext": []
```

2021-12-13 12:49 UTC, vincenthoogsteder commented on schema/base_schema.json5
> +        "referer": {
check, closing this for this round then

2021-12-13 12:50 UTC, sdirosa commented on schema/base_schema.json5
> +    },
Very nice, even better 👌🏼

2021-12-13 13:03 UTC, sdirosa commented on schema/base_schema.json5
>      },
There's a missing curly bracket here, closing the properties object:

```suggestion
      }
    },
```

2021-12-13 13:04 UTC, sdirosa commented on schema/base_schema.json5
> +      "requiresContext": ["PressableContext."]
```suggestion
      "requiresContext": ["PressableContext"]
```

2021-12-13 13:53 UTC, sdirosa commented on backend/tests/schema/test_schema.py
>              "time":1630049334860,
Updated this test fixture to reflect the new schema

2021-12-13 13:53 UTC, borft commented on backend/requirements-dev.txt
> +autopep8==1.6.0
:+1: 
but, I don't think we need this specific version though

2021-12-13 13:54 UTC, borft commented on backend/requirements-dev.txt
> +autopep8==1.6.0
```suggestion
autopep8
```

2021-12-13 13:54 UTC, sdirosa commented on schema/base_schema.json5
>      },
@vincenthoogsteder FYI: 

Parent-child order matters in the schema JSON so I've moved these two definitions up here.

What happens otherwise is that the other Events get generated first and they cannot find their parents.

2021-12-13 14:09 UTC, sdirosa commented on backend/requirements-dev.txt
> +autopep8==1.6.0
Ah thanks, I approved your suggestion

2021-12-13 15:36 UTC, sdirosa approved these changes

2021-12-13 20:11 UTC, sdirosa commented
@vincenthoogsteder BE and FE are fully up to date. 

I found one small bug to fix in the TS generator script, but it's minor stuff and does not affect functionality. I'll take care of that tomorrow.

Next steps: 
- Publish and test new packages with Verdaccio.
- When happy, publish new versions of the packages to NPM (v0.0.2).
- Upgrade Tracker instrumentation to v0.0.2 on Website and Docs.
- And, of course, I need to update the Trackers API Reference docs.

2021-12-14 15:06 UTC, sdirosa commented on tracker/core/utilities/src/generator.js
> +
@borft Look at my beautiful fix :)

I think we should formalize the pipeline a bit better as we briefly discussed. For now this works nicely.

2021-12-14 15:10 UTC, sdirosa commented
Pushed some new changes:
- Added tagRootLocation to BrowserTracker 
- Added tagRootLocation to AngularTracker 
- Fixed a TS definition generator bug: events with obligatory attributes get assigned optional context parameters
- Got rid of automatically tracked Visibility events on regular Sections

2021-12-14 19:39 UTC, sdirosa commented on schema/base_schema.json5
> +    },
Discussion planned for Thursday, resolving this

2021-12-23 19:23 UTC, vincenthoogsteder commented
@sdirosa @borft pls review latest updates

2021-12-24 09:32 UTC, borft commented on schema/base_schema.json5
> +      "description": "AbstractLocationContext are the abstract parents of all Location Contexts. Location Contexts are meant to describe where an event originated from in the visual UI.",
are -> is

2021-12-24 09:37 UTC, vincenthoogsteder commented on schema/base_schema.json5
> +      "description": "AbstractLocationContext are the abstract parents of all Location Contexts. Location Contexts are meant to describe where an event originated from in the visual UI.",
nice catch

2021-12-24 09:41 UTC, borft approved these changes
lgtm

2022-01-03 09:17 UTC, merged