level support in reset_index
objectiv/objectiv-analytics pull request #369
Opened 2022-01-10 13:34 UTC by KathiaBarahona

2022-01-11 16:31 UTC, thijs-obj requested changes
One small change needed I think

2022-01-11 16:31 UTC, thijs-obj commented on bach/tests/functional/bach/test_df_reset_index.py
> +
Can I suggest one more test case:
``` python
def test_reset_index_no_change():
    bt = get_bt_with_test_data()
    bt = bt.set_index(['skating_order', 'city'], append=True)
    lbt = bt.reset_index(level=[])
    assert list(lbt.index.keys()) == list(bt.index.keys())
```

This doesn't currently work, but I think we should make it pass. It works with Pandas

2022-01-11 16:31 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        level: Optional[Union[str, Sequence[str]]] = None,
I think this is good.

@hendrik-obj do you agree, or do we need to support integers here for the columns too?

2022-01-12 07:55 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_df_reset_index.py
> +
thanks, nice catch!

2022-01-12 09:06 UTC, thijs-obj reviewed
Looks good to me. But let's wait for @hendrik-obj to reply too

2022-01-12 09:56 UTC, hendrik-obj approved these changes
lgtm!

2022-01-12 13:59 UTC, thijs-obj approved these changes

2022-01-12 14:22 UTC, merged