[WIP] df describer
objectiv/objectiv-analytics pull request #374
Opened 2022-01-12 16:18 UTC by KathiaBarahona

2022-01-13 09:40 UTC, KathiaBarahona commented on bach/bach/describe.py
> +    SupportedStats.UNIQUE: 'count( distinct {col})',
@thijs-obj Not sure if we already have smth similar to this somewhere.

2022-01-14 13:54 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        return df
should had opened another PR for this, but kinda noticed I needed it when I was finishing

2022-01-14 15:43 UTC, jansentom reviewed
Impressive that you managed to get this working in your first week! 
A few general remarks:
- Very nice approach, and most of it quite easy to review.
- You mix  "column" or "columns" with "series" to name the individual data series. We use series to stick to Pandas jargon, although columns is not wrong, it's nice to have some consistency there. 
- I did not fully finish the review, leaving some for @thijs-obj on Monday ;)

2022-01-14 15:43 UTC, jansentom commented on bach/bach/series/series.py
> +            base_expression = f'{expression}({{}})'
very clean, nice!

2022-01-14 15:43 UTC, jansentom commented on bach/bach/describe.py
> +class DataFrameDescriber:
I did not review this class in detail yet, leaving that to @thijs-obj for Monday ;)

2022-01-17 08:31 UTC, KathiaBarahona commented on bach/bach/describe.py
> +            stat_df = stat_df.to_frame() if isinstance(stat_df, Series) else stat_df
not really, mypy was complaining :)

2022-01-17 08:33 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +            df._data[col.name] = col.round(decimals)
I tried doing `_apply_func_to_series` but got a bunch of problems with the renaming of columns, so that's why I decided this approach instead of doing some weird hack. Eg: `column_A_round`. Also I wouldn't consider `round` as an aggregation, it's more like a `transformation` operation, so that's why I also didn't wanted to mix both concepts

2022-01-17 08:34 UTC, KathiaBarahona commented on bach/bach/describe.py
> +def describe_frame(
I plan to use it for `Series.describe`, so I'm just avoiding future code duplication

2022-01-17 08:35 UTC, KathiaBarahona commented on bach/bach/series/series_numeric.py
> +            partition, 'stddev_samp', 'double precision', skipna=skipna, cast_db_type=True,
I started to get errors since db `Numeric` type isn't supported. I didn't wanted to add it to the type register, since I was not really sure how it might affect other functionalities.

2022-01-17 09:56 UTC, thijs-obj commented on bach/bach/series/series_numeric.py
> +                partition, 'avg', 'double precision', skipna=skipna, cast_db_type=True,
I realise you din't type this. But I think the `'double precision'` here is sort of a bug. `'double precision'` is one of the `dtype_aliases` of `'float64'`, so this works. Most `dtype_aliases` exist for Pandas compatibility (e.g. in pandas you can say `s.astype('f8')` which is the same as `s.astype('float64')`). However, the reason that 'double precision' is an alias is more for historic reasons in our code base than for pandas compatibility.

Anyway long story short, the dtype is `float64`, let's write that here instead of `double precision` as that only obscures things imho

2022-01-17 10:03 UTC, thijs-obj commented on bach/bach/series/series.py
> +            if cast_db_type and is_supported_db_dtype(derived_dtype):
I think this is a bit tricky. if `cast_db_type` is set, but `is_supported_db_dtype(derived_dtype)` is False then we'll just not do anything here. But shouldn't we raise an error in that case?

It happens to be that we call this function with `dtype='double precision'`, and `'double precision'` happens to be the `db_dtype` of a `float64` in Postgres, so this works. But if we called this with `dtype='float64', cast_db_type=True` then it would just not do anything

2022-01-17 10:07 UTC, thijs-obj commented on bach/bach/types.py
> +    return db_dtype in _registry.db_dtype_to_series
There is some weird stuff in `TypeRegistry` because of cyclic imports. As a result if you just use `_registry`, then `_real_init()` might not have run and this function doesn't work yet. Better to add a bit of indirection here and call a function inside `_registry`, that makes sure that `_real_init()` has been called.


For example, I was just curious what this function would yield, so I typed this in ipython:
```
In [1]: from bach.types import is_supported_db_dtype, _registry

In [2]: is_supported_db_dtype('double precision')
Out[2]: False
```

2022-01-17 10:07 UTC, thijs-obj commented on bach/bach/types.py
> +    return db_dtype in _registry.db_dtype_to_series
Or if you know a more elegant solution to the loading of `TypeRegistry` then that could be tackled as a separate thing

2022-01-17 10:10 UTC, thijs-obj commented on bach/bach/dataframe.py
> +            df._data[col.name] = col.round(decimals)
I quite like this approach. Here I only have to look at the code here to understand what happens, otherwise I'll also have to look at `_apply_funct_to_series()`. Do agree with Tom on not mutating the current DataFrame, Pandas doesn't do that either. Think that's fixed now tho :+1:

2022-01-17 14:19 UTC, thijs-obj commented on bach/tests/functional/bach/test_df_describe.py
> +def test_df_categorical_describe() -> None:
I think we should have some tests here for the actual user interface, i.e. a test that runs `df.describe()`.

Now we only have tests for the code that `df.describe()` calls, but I think in the end the main thing we want is to be sure that we don't have regressions in the end-user's interface

2022-01-17 14:24 UTC, thijs-obj commented on bach/bach/describe.py
> +    def _append_stats(self, stats_1_df: DataFrame, stats_2_df: DataFrame) -> DataFrame:
I think this works, but this generates very long sql statement. Would it be possible to `union` all the statistics in one big sql statement?. Something like:

```
select * from {{stat1}}
union
select * from {{stat2}}
union
select * from {{stat3}}
union
select * from {{stat4}}
```

2022-01-17 14:39 UTC, thijs-obj commented on bach/bach/describe.py
> +        self._process_params()
small comment, but can we not just copy everything that is in `_process_params()` and put it here? Now in reviewing I have to go to another function to see what is actually happening here. Putting it in another function doesn't seem to add anything

2022-01-17 15:18 UTC, KathiaBarahona commented on bach/bach/series/series_numeric.py
> +                partition, 'avg', 'double precision', skipna=skipna, cast_db_type=True,
sure, the reason I wrote "double precision" is because I needed to cast the column as it, that's why I'm passing `cast_db_type=true`. I know this is a hacky solution, but I had no other way to avoid the `numeric` db type error. If you have a better solution, let me know

2022-01-17 15:58 UTC, KathiaBarahona commented on bach/bach/describe.py
> +        self._process_params()
I rather have a separate function where we dump all sort of validations or "re processing" stuff for now. As I mentioned, we can avoid such things using [pydantic's validators](https://pydantic-docs.helpmanual.io/usage/validators/). We can discuss about it later.

2022-01-17 16:32 UTC, KathiaBarahona commented on bach/bach/describe.py
> +class DataFrameDescriber:
1. Yes, I'd just changed `described_columns` to `series_to_describe`. This is now a property for the class. Also changed `_get_stat_type_based_on_all_series` to `_set_stat_type_based_on_all_series`, so know it's a bit more clear where we actually set both properties.
2. I think it won't be that efficient, since `describe` generates UNIONs, therefore the final query for the dataframe will be a bunch of subqueries containing Unions which we will later need to join, so it actually sounds way more complex than expected.

2022-01-18 07:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +    def round(self, decimals: int = 0):
Perhaps it would be an idea to put this in another PR with functional tests etc. and merge that PR first? Then this PR becomes a bit smaller

2022-01-19 10:07 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +    def round(self, decimals: int = 0):
agree!

2022-01-19 10:33 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +    def round(self, decimals: int = 0):
https://github.com/objectiv/objectiv-analytics/pull/385

2022-01-31 18:13 UTC, KathiaBarahona commented on bach/bach/describe.py
> +def describe_frame(
done! Now we call `DescribeOperation` in both classes

2022-01-31 18:14 UTC, KathiaBarahona commented on bach/bach/describe.py
> +    def _append_stats(self, stats_1_df: DataFrame, stats_2_df: DataFrame) -> DataFrame:
Done!

2022-01-31 18:15 UTC, KathiaBarahona commented on bach/bach/describe.py
> +class DataFrameDescriber:
This changed, I followed a similar convention as in `ConcatOperation`. Now we don't set any attribute in any function

2022-01-31 18:16 UTC, KathiaBarahona commented on bach/bach/describe.py
> +        self._process_params()
ended up moving this to `__init__`

2022-01-31 18:17 UTC, KathiaBarahona commented on bach/bach/describe.py
> +    SupportedStats.FREQ: DataFrame.mode,
The result of  `freq` is different than to Pandas. We are returning the most frequent value, meanwhile Pandas returns the frequency number of the most frequent value.

2022-01-31 18:18 UTC, KathiaBarahona commented on bach/bach/describe.py
> +    SupportedStats.FREQ: DataFrame.mode,
To be honest, I find our result more significant, but that's my personal opinion. @hendrik-obj  what do you think about this? should we stick to Pandas?

2022-02-01 14:05 UTC, jansentom requested changes
Hi Kathia, 

Very cool that you got this to work. I do find the "how" quite complex, mainly due to all the dtype magic.

All stats functions in `DataFrame` (e.g. `df.sum()`) do their own series selection based on type if required. Could we not use those directly, and only use include/exclude to filter the series we want to process beforehand?


PS It's really nice that everything is typed.

2022-02-02 11:17 UTC, KathiaBarahona commented on bach/bach/describe.py
> +    SupportedStats.FREQ: DataFrame.mode,
removed!

2022-02-02 11:18 UTC, KathiaBarahona commented on bach/bach/describe.py
> +_SERIES_TYPE_X_SUPPORTED_STAT: Dict[Type, Tuple[SupportedStats, ...]] = {
yup, as agreed I removed this dictionary and evaluate all SupportedStats for supported dtypes.

2022-02-02 11:20 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        :param exclude: dtypes to be excluded
what do you mean? include + exclude?

2022-02-02 12:05 UTC, jansentom commented on bach/bach/dataframe.py
> +        :param exclude: dtypes to be excluded
ignore that. Not interesting enough.

2022-02-02 20:06 UTC, jansentom reviewed
This is starting to look nice! I did a review mostly on structure and details, and left some comments. One to address together tomorrow after standup, the rest small details / nitpicks. Will do a functional review again once we fix the last structural things. See you tmr!

2022-02-02 20:06 UTC, jansentom commented on bach/bach/series/series_numeric.py
> +            partition, 'stddev_samp', 'double precision', skipna=skipna, cast_db_type=True,
```suggestion
            partition, 'stddev_samp', 'float64', skipna=skipna, cast_db_type=True,
```

2022-02-02 20:06 UTC, jansentom commented on bach/bach/series/series_numeric.py
> +                partition, 'avg', 'double precision', skipna=skipna, cast_db_type=True,
```suggestion
                partition, 'avg', 'float64', skipna=skipna, cast_db_type=True,
```

2022-02-02 20:06 UTC, jansentom commented on bach/bach/series/series_numeric.py
> +                partition, 'avg', 'double precision', skipna=skipna, cast_db_type=True,
the cast thingy is fine, it's just the "old bug" in there. See suggestion below.

2022-02-03 11:14 UTC, KathiaBarahona commented on bach/bach/describe.py
> +        numerical_series_names = [
tried to do it as in `_calculate_stat`, but now that I remember we had to define `quantile` method in `Series`, soo it won't work. I'll add a comment explaining this

2022-02-03 11:20 UTC, KathiaBarahona commented on bach/bach/describe.py
> +_SUPPORTED_SERIES_TYPES: Tuple[Type, ...] = (
added comment and issue https://github.com/objectiv/objectiv-analytics/issues/430

2022-02-03 11:21 UTC, KathiaBarahona commented on bach/bach/types.py
> +    return db_dtype in _registry.db_dtype_to_series
removed, we no longer need this

2022-02-03 11:22 UTC, KathiaBarahona commented on bach/bach/series/series_numeric.py
> +                partition, 'avg', 'double precision', skipna=skipna, cast_db_type=True,
casting hack was removed, seems everything is ok since all the type casting is done by `DataFrameConcatOperation`.

2022-02-03 20:07 UTC, jansentom approved these changes
yeeehaa :cowboy_hat_face:

2022-02-07 21:27 UTC, thijs-obj approved these changes
Have some small things on comments. But code wise looks good to me. Don't think this would need another round of review

2022-02-07 21:27 UTC, thijs-obj commented on bach/bach/describe.py
> +    In order to implement this class you should provide the following params:
```suggestion
    In order to instantiate this class you should provide the following params:
```

2022-02-07 21:27 UTC, thijs-obj commented on bach/bach/describe.py
> +    datetime_is_numeric: A boolean specifying if datetime series should be treated as numeric columns
Would be good to mention here too that this parameter is not supported.

2022-02-07 21:27 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        Returns descriptive statistics, it will vary based on what is provided
Can we not be more specific than `it will vary based on what is provided`? The reader doesn't really gain much by reading that.

2022-02-07 21:46 UTC, thijs-obj commented on bach/bach/describe.py
> +        describe_df = describe_df.sort_values(by=f'{self.STAT_SERIES_NAME}_position')
almost forgot. Instead of `f'{self.STAT_SERIES_NAME}_position'` can we not name this column something like `__stat_position`. We could then say that any column starting with double underscores is a reserved name, and users shouldn't use that.

Not really a big deal now, as we have very few users, but it will by quite confusing for users if they happen to have a column that's called `stat_position`. That will give weird results, even tho the users cannot know that we use that column for sorting purposes as it doesn't show up in the results.

2022-02-09 11:00 UTC, merged