df.sort_index implementation
objectiv/objectiv-analytics pull request #398
Opened 2022-01-21 11:19 UTC by KathiaBarahona

2022-01-21 12:50 UTC, jansentom requested changes
Very nice already. Some small fixes required, but almost ready to ship I think! Should be doable before drinks :beer:

2022-01-21 12:50 UTC, jansentom commented on bach/bach/dataframe.py
> +        index_columns = []
I find it a bit confusing that `index_columns` has the same name as `self.index_columns`. Perhaps `sort_series` would be better?

2022-01-21 12:50 UTC, jansentom commented on bach/bach/dataframe.py
> +         If not specified, all index columns are used
We try to abstract away from the database here. Please use `series` instead of `columns`.  (Applies in a few other places as well)

2022-01-21 12:50 UTC, jansentom commented on bach/tests/functional/bach/test_df_sort_index.py
> +            ['Ljouwert', 1, 5, 'Camminghaburen'],
I kind of like that you're using these unpronounceable fixtures too :)

2022-01-21 12:50 UTC, jansentom commented on bach/bach/dataframe.py
> +            level_name = idx_l if isinstance(idx_l, str) else self.index_columns[idx_l]  # type: ignore
We should probably fix the reason the type ignore is required instead.

2022-01-21 12:50 UTC, jansentom commented on bach/bach/dataframe.py
> +            if level_name not in index_columns:
I don't think this is correct as the length of the returned list now has a different length than the length of the ascending list in the calling method? (see comment in tests below too)

2022-01-21 12:50 UTC, jansentom commented on bach/tests/functional/bach/test_df_sort_index.py
> +    result = btr.sort_index(level=['platforms', 0, 'platforms'])
This breaks if you give `ascending=[True,True,True]`. We should probably test for that and fix it.

2022-01-21 13:04 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        index_columns = []
mmm IMHO it's better `index_columns` just in case other future methods might need to filter out the indexes by level. I don't want it to be sticked just for sorting implementations :)

2022-01-21 13:05 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +            if level_name not in index_columns:
good catch, I'll probably remove this condition and see if that causes any error

2022-01-21 13:12 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +            level_name = idx_l if isinstance(idx_l, str) else self.index_columns[idx_l]  # type: ignore
actually, there was no need. I thought so because pycharm was complaining

2022-01-21 14:41 UTC, jansentom approved these changes
LGMT! Some stuff to discuss with @thijs-obj , but no blockers from my side to merge.

2022-01-21 14:41 UTC, jansentom commented on bach/bach/dataframe.py
> +        index_columns = []
What about `selected_columns` then? :) If you disagree, @thijs-obj can decide what he likes better ;)

2022-01-21 14:41 UTC, jansentom commented on bach/bach/dataframe.py
> +        sort_by = self.index_columns if not level else self._get_index_columns_by_level(level)
I realise that you are not responsible for the naming of `self.index_columns`, but that it'd be better to name that `index_series`. If you and Thijs agree, we can add that to the backlog

2022-01-21 14:49 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        index_columns = []
I agree with that name :+1:

2022-01-21 14:50 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        sort_by = self.index_columns if not level else self._get_index_columns_by_level(level)
If we want to avoid using the term `column`, let's rename it :)

2022-01-21 15:15 UTC, jansentom commented on bach/bach/dataframe.py
> +        sort_by = self.index_columns if not level else self._get_index_columns_by_level(level)
Yeah, I'd like that for all stuff that's not directly SQL. It's probably a bit big to include in this PR. Can you make an issue so we can include it on Monday?

2022-01-24 09:28 UTC, thijs-obj commented on bach/tests/functional/bach/test_df_sort_index.py
> +            ['Snits', 2, 6, 'Sneek'],
This test is not deterministic. If we sort on `['platforms', 'town', 'platforms']` then these two rows might be returned as either
```
            ['Snits', 2, 7, 'Sneek Noord'],
            ['Snits', 2, 6, 'Sneek'],
```
or
```
            ['Snits', 2, 6, 'Sneek'],
            ['Snits', 2, 7, 'Sneek Noord'],
```
Both are correct.


This might be related to Tom's comment about this breaking when `ascending=[True, True, True]` ?

2022-01-24 09:33 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        sort_by = self.index_columns if not level else self._get_index_columns_by_level(level)
I agree that consistent naming is very important.

We have used columns in quite a few places already, but I think Tom is right that we probably should use 'Series' instead of 'columns' in most places.

Generally I am not sure that we should automatically always stick with the Pandas nomenclature tho? Some of the Pandas naming is really vague I think, and not very accessible for people from outside pandas. E.g. 'level' for indices, took me quite a while to figure out that that meant columns :) Perhaps we could use all the pandas naming, but also use 'sql' terminology like "columns" in the docstrings? Let's discuss this in the Data Science channel, or a meeting.

2022-01-24 09:34 UTC, thijs-obj reviewed
One small comment about a test, otherwise looks good to me

2022-01-24 09:36 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_df_sort_index.py
> +            ['Snits', 2, 6, 'Sneek'],
mm nope, the issue with the `ascending=[True, True, True]` is that I was just considering one time each level. So if user provides `['platforms', 'town', 'platforms']` with a list of ascending values, it will raise an error since `len(level) != len(ascending)`. 

Tho, your comment is valid. I will fix this test :+1:

2022-01-24 10:34 UTC, thijs-obj commented on bach/bach/dataframe.py
> +            level_name = idx_l if isinstance(idx_l, str) else self.index_columns[idx_l]  # type: ignore
but now it's back

2022-01-24 10:50 UTC, merged