implement NotSet in copy_override for DataFrame and Series, more typing
objectiv/objectiv-analytics pull request #426
Opened 2022-01-28 14:48 UTC by KathiaBarahona

**Issue**:  https://github.com/objectiv/objectiv-analytics/issues/411

## Description
Following @thijs-obj  implementation in https://github.com/objectiv/objectiv-analytics/pull/406#discussion_r792060095, started using NotSet enum for `DataFrame.copy_override` and `Series.copy_override`. 

## Changes
* Moved NotSet enum to `constants.py` module
* Added typing for `Series.copy_override` params. (This led to further changes)
* Removed `List` typing for `group_by` param. This removes `group_by=[None]` hack.
* Started typing parameters with default None value as `Optional`. This is because [mypy's implicit optional behavior might change in a future](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#:~:text=you%20can%20use%20the%20--no-implicit-optional%20command-line%20option%20to%20stop%20treating%20arguments%20with%20a%20none%20default%20value%20as%20having%20an%20implicit%20optional%5B...%5D%20type.%20it%E2%80%99s%20possible%20that%20this%20will%20become%20the%20default%20behavior%20in%20the%20future.)

2022-01-28 14:50 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        renamed_value: DataFrameOrSeries = value.copy_override(name=key)
I found a bit nasty we assign a DataFrame to a variable that initially was a Series. See line 980

2022-01-28 14:52 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +        klass: type = self.__class__ if dtype is None else get_series_type_from_dtype(dtype)
Just followed this [hack](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#:~:text=checkers%20and%20IDEs.-,The%20type%20of%20class,assume%20the%20following%20classes%3A,-class%20User%3A%0A%20%20%20%20%23%20Defines). If there's another way to type this, please let me know

2022-01-31 10:00 UTC, jansentom requested changes
Nice improvement. Some remarks in the comments. Main ones:
- sql_models now depends on Bach, that's not preferred. (you could not have known)
- some forgotten docstring stuff

2022-02-02 11:31 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +        base_node: Optional[TSqlModel] = None,
Unfortunately, mypy started complaining since sometimes it receives a BachSqlModel :(

2022-02-02 11:35 UTC, KathiaBarahona commented on bach/bach/constants.py
> +from enum import Enum
moved it to sql_models package, so now the dependency should be one way :grimacing:

2022-02-02 11:39 UTC, KathiaBarahona commented
> Nice improvement. Some remarks in the comments. Main ones:
> 
> * sql_models now depends on Bach, that's not preferred. (you could not have known)
> * some forgotten docstring stuff

Thanks for the docstring stuff, my brain automatically ignores them !

2022-02-02 12:04 UTC, jansentom approved these changes
LGTM!

2022-02-02 12:04 UTC, jansentom commented on bach/bach/dataframe.py
> -        create new index and data series iff index and/or series are not given. `single_value` determines
https://www.collinsdictionary.com/dictionary/english/iff :)

2022-02-02 12:32 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> -        create new index and data series iff index and/or series are not given. `single_value` determines
the more you know haah

2022-02-02 18:07 UTC, merged

2022-02-08 10:18 UTC, thijs-obj commented on bach/bach/series/series.py
> +        base_node: Optional[TSqlModel] = None,
I think this should be `BachSqlModel`, as that is what the `__init__` function expects.
```suggestion
        base_node: Optional[BachSqlModel] = None,
```

2022-02-08 10:21 UTC, thijs-obj commented on bach/bach/series/series.py
> +        klass: type = self.__class__ if dtype is None else get_series_type_from_dtype(dtype)
Not something to change in this PR, but something for another issue. I think we should have a separate function `copy_override_dtype()` and remove the `dtype` parameter from this function. Then we would always know for sure what the return type is here, and mypy would for example be able to detect that `base_node` should be a `BachSqlModel` and not just a sub-class of `SqlModel` (see comment above)

2022-02-10 07:49 UTC, thijs-obj commented on bach/bach/series/series.py
> +        base_node: Optional[TSqlModel] = None,
https://github.com/objectiv/objectiv-analytics/pull/463 fixes this