drop_duplicates implementation
objectiv/objectiv-analytics pull request #428
Opened 2022-02-01 16:12 UTC by KathiaBarahona

**Issue**:https://github.com/objectiv/objectiv-analytics/issues/421

## Description
Implemented `DataFrame.drop_duplicates` and `Series.drop_duplicates`.  This feature implements functionalities such as:
`SELECT DISTINCT` and `FIRST_VALUE`, `LAST_VALUE` window functions.

## Checklist:
- [x] Tests
- [x] Update docstrings
- [x] Update documentation

2022-02-01 16:13 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +            df = df._apply_distinct()
considered doing another function for this, but was going to end up with duplicated code.

2022-02-01 16:14 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        )
@jansentom is it worth it to create `DistinctSqlModel` for this? DataFrame class is a bit crowded, tho I'm not sure where to define it, if that's the case

2022-02-01 16:15 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +        return self
@jansentom  noticed we didn't have this (needed for `inplace`=True). Do you this a bit dangerous?

2022-02-01 20:08 UTC, jansentom requested changes
Hi Kathia,

Nice work, it's al quite clean already, and the tests looks great. Also kudos for not forgetting the docs index thingies! 
I left some comments, one big one that I think is important enough to request changes, the rest is good to go (with maybe some minor polishing). See you tmr. Let's sync in the morning if you have questions.

2022-02-01 20:08 UTC, jansentom commented on bach/tests/functional/bach/test_df_drop_duplicates.py
> +    expected_pdf = pd.DataFrame(
wouldn't it be nice (:musical_note: beach boys, yeeheaaa) to do `pdf.drop_duplicates( ... )` instead in all tests?

2022-02-02 08:14 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        series_to_combine = list(subset or self.data_columns)
mmm subset has different multiple types, I rather have another variable for this. I can rename it to `duplicated_on`?

2022-02-02 08:16 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        )
yup,  I was not feeling comfortable with this as well. Adding a distinct parameter to `get_current_node` and `materialize`  sounds good to me.

2022-02-02 08:17 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +        self._index = series.index.copy()
hah good catch, thanks!

2022-02-02 08:17 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +                window=df.groupby(by=series_to_combine).window(),
yup, forgot to test that actually. Thanks for the reminder

2022-02-02 08:24 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +            return None
indeed, but IMHO it's a bit more readable this way and it's not a lot of code been duplicated. [return early pattern](https://medium.com/swlh/return-early-pattern-3d18a41bba8) :)

2022-02-02 08:27 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_df_drop_duplicates.py
> +    expected_pdf = pd.DataFrame(
A time ago mr @thijs-obj said that he preferred to see the data that it was compared to. But I do agree with you because I'm ~efficient~ lazy

2022-02-02 08:36 UTC, jansentom commented on bach/tests/functional/bach/test_df_drop_duplicates.py
> +    expected_pdf = pd.DataFrame(
In that case, let's do both. I kin of agree that it's nice to review if the data is there as well.

2022-02-02 08:39 UTC, jansentom commented on bach/bach/dataframe.py
> +            return None
I don't feel too strongly about this. Okay to keep.

2022-02-02 08:42 UTC, jansentom commented on bach/bach/dataframe.py
> +        series_to_combine = list(subset or self.data_columns)
ah, yes, I overlooked that. In that case `dedup_on` for `subset` and something like `dedup_data` for `non_subset`?

2022-02-02 08:43 UTC, jansentom commented on bach/bach/series/series.py
> +        return self
Missed this comment, think this is okay

2022-02-02 08:44 UTC, jansentom commented on bach/tests/functional/bach/test_df_drop_duplicates.py
> +    expected_pdf = pd.DataFrame(
With a simple assert we'll have both. I'd like that!

2022-02-02 10:05 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +            return None
removed the `if keep is False` block. So, no duplicated code anymore!

2022-02-02 10:06 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_df_drop_duplicates.py
> +    expected_pdf = pd.DataFrame(
done!

2022-02-02 12:00 UTC, jansentom approved these changes
One minor comment left. After that's resolved, good to merge IMHO. @hendrik-obj check this out!

2022-02-02 12:15 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +            window = df.groupby(by=dedup_on).window(end_boundary=WindowFrameBoundary.FOLLOWING)
sounds reasonable

2022-02-02 18:03 UTC, merged