Unstack
objectiv/objectiv-analytics pull request #442
Opened 2022-02-03 19:40 UTC by hendrik-obj

Unstack for Bach series. It has an `aggregation` (unlike pandas) parameter. This is done so we don't need to check duplicate indexes. empty values in indexes are not supported, as this will results in None or np.nan named columns, which is not supported in Bach.

2022-02-04 11:51 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +        df = self.to_frame().reset_index().groupby(remaining_indexes)  # type: ignore
```suggestion
        df = self.to_frame()
        df.reset_index(inplace=True)
        df = df.groupby(remaining_indexes)
```
mypy complains because `reset_index` has `Optional` typing due to `inplace=True` case

2022-02-04 12:13 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +        df = self.to_frame().reset_index().groupby(remaining_indexes)  # type: ignore
```suggestion
        name_index_last, series_last = index_dict.popitem()
        df = self.to_frame()
        df.reset_index(inplace=True)
        values = df[series_last.isnull()].to_numpy()
        if not values:
            raise ValueError("index contains empty values, cannot be unstacked")
        
        name_series = self.name
        remaining_indexes = list(index_dict.keys())
        df = df.groupby(remaining_indexes)
```

mypy complains because `reset_index` has `Optional` as return type because of `inplace = True` case.

2022-02-04 12:49 UTC, KathiaBarahona requested changes
Works good. Added a couple of improvements, also I think we should be careful with the tests since the order of the columns might change because there's no sorting on the values of the level to be unstacked.

2022-02-04 12:49 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +                aggregation: str = 'max'):
```suggestion
                aggregation: str = 'max') -> 'DataFrame':
```

2022-02-04 12:49 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +        return df.copy_override(series=series_dict).materialize()  # type: ignore
```suggestion
        fill_series = const_to_series(base=self, value=fill_value, name='fill_value')

        for column in values:
            new_column_name = str(column)
            new_const_series = const_to_series(self, column, new_column_name)
            series_dict[new_column_name] = df.all_series[name_series].copy_override(
                name=new_column_name,
                expression=AggregateFunctionExpression.construct(
                    f"{aggregation}(case when {{}} = {{}} then {name_series} else {{}} end )",
                    series_last,
                    new_const_series,
                    fill_series,
                )
            )

        unstacked_df = df.copy_override(series=series_dict)
        unstacked_df.materialize(inplace=True)
        return unstacked_df
```
**suggestion** how about this? it is a bit more readable. I think the if-else block is not necessary, you can do raise the fill value `TypeError` before iterating over the values. Also creating a fill_value series with null will be the same as not having an else condition for the case statement.

2022-02-04 12:49 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +
```suggestion
        if aggregation not in ['max', 'min']:
            raise ValueError(f"aggregation is '{aggregation}', should be 'min' or 'max'")

        if fill_value and value_to_dtype(fill_value) != self.dtype:
            raise TypeError('fill_value should be of same type as the index that is unstacked')

```

2022-02-07 15:03 UTC, jansentom reviewed
Nice functionality, but I have some comments.

2022-02-07 16:50 UTC, hendrik-obj commented on bach/bach/series/series.py
> +        unstacked_df.materialize(inplace=True)
removed it; I added it before because sometimes it can lead to an inconvenient workflow if you have to manually materialize, but that another discussion indeed.

2022-02-07 16:50 UTC, hendrik-obj commented on bach/bach/series/series.py
> +import numpy as np
changed

2022-02-07 16:50 UTC, hendrik-obj commented on bach/bach/series/series.py
> +        values = series_last.unique().values
added a test.

2022-02-07 16:50 UTC, hendrik-obj commented on bach/bach/series/series.py
> +            raise ValueError(f"aggregation is '{aggregation}', should be 'min' or 'max'")
made some adjustments: now it uses aggregate, so all supported methods for aggregate now work. first and last would be interesting, but I think are separate issues from unstack. once aggregate supports it, they are now automatically supported.

2022-02-07 16:50 UTC, hendrik-obj commented on bach/bach/series/series.py
> +        values = series_last.unique().values
added a test.

2022-02-07 16:50 UTC, hendrik-obj commented on bach/bach/series/series.py
> +            raise ValueError(f"aggregation is '{aggregation}', should be 'min' or 'max'")
made some adjustments: now it uses aggregate, so all supported methods for aggregate now work. first and last would be interesting, but I think are separate issues from unstack. once aggregate supports it, they are now automatically supported.

2022-02-07 16:50 UTC, hendrik-obj commented on bach/bach/series/series.py
> +        return unstacked_df
added it to the docstring.

2022-02-07 16:50 UTC, hendrik-obj commented on bach/bach/series/series.py
> +        return unstacked_df
added it to the docstring.

2022-02-07 20:04 UTC, jansentom approved these changes
LGTM, nice addition. The only thing left to do is to add it to [the reference](https://objectiv.io/docs/modeling/DataFrame#reference-by-function)

2022-02-07 20:04 UTC, jansentom commented on bach/bach/series/series.py
> +            new_series_aggregated = new_series.aggregate(aggregation, group_by=df.group_by)
This is sweet!

2022-02-08 11:56 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +            new_series_aggregated = new_series.aggregate(aggregation, group_by=df.group_by)
Not the fanciest solution for the mypy issue, but this shall work:
```python
            new_series_aggregated = cast(
                Series, new_series.aggregate(aggregation, group_by=df.group_by)
            )
```
@hendrik-obj

2022-02-08 11:58 UTC, KathiaBarahona approved these changes
lgtm

2022-02-08 12:20 UTC, merged