Kathiabarahona/df fillna
objectiv/objectiv-analytics pull request #492
Opened 2022-02-18 11:04 UTC by KathiaBarahona

`fillna` for `DataFrame`. Supporting `value`, `ffill`, `bfill` methods for filling null gaps.

Still missing tests, docstrings and disclaimer about non-deterministic results

2022-02-18 11:04 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +        """
I'll update this, also need to add a test case

2022-02-18 11:05 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +    ) -> Optional['DataFrame']:
here too

2022-02-18 11:05 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +    ) -> Optional['DataFrame']:
same :)

2022-02-20 19:51 UTC, jansentom requested changes
Smart way to do this, took me a while to get why it worked. I do have some problems with some parts of the implementation though, but they should not be super hard to address.

2022-02-20 19:51 UTC, jansentom commented on bach/bach/dataframe.py
> +        df.materialize(inplace=True)
What happens here is quite smart/magical. I needed to look at the SQL generated to actually understand:
in pseudo-sql:
```sql
sum(case when "series_name" is null then 0 else 1 end) over ( order by "df.order_by" asc RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as "__partition_series_name"
```
I do think it needs a very detailed explanation here in the code.

2022-02-20 19:51 UTC, jansentom commented on bach/bach/dataframe.py
> +        df.materialize(inplace=True)
Please give name to the materialization btw
```suggestion
        df.materialize(node_name='fillna_partitioning', inplace=True)
```

2022-02-20 19:51 UTC, jansentom commented on bach/tests/functional/bach/test_df_fillna.py
> +    [None, None, 1, None],
Easier to read:

```suggestion
    [None, None, None, None],
    [3,    4,    None, 1],
    [None, 3,    None, 4],
    [None, 2,    None, 0],
    [None, None, None, None],
    [1,    None, None, None],
    [None, None, None, None],
    [None, None, 1,    None],
```

2022-02-20 19:51 UTC, jansentom commented on bach/tests/functional/bach/test_df_fillna.py
> +    [None, None, 1, None],
I'm also missing test cases with sparse data, e.g. `None, 1, None, None, 2, None, 3, None`

2022-02-20 19:51 UTC, jansentom commented on bach/tests/functional/bach/test_df_fillna.py
> +import numpy as np
Don't think this is used?

2022-02-20 19:51 UTC, jansentom commented on bach/tests/functional/bach/test_df_fillna.py
> +import pandas as pd
Does pandas give different results in these tests? Could we compare to pandas output?

2022-02-20 19:51 UTC, jansentom commented on bach/bach/series/series.py
> +    def window_sum(self, window: WrappedWindow = None):
I don't think this method is required. Also see comment in `ffill()` implementation above.

2022-02-20 19:51 UTC, jansentom commented on bach/bach/dataframe.py
> +            df[partition_name] = self.all_series[series_name].copy_override(
This needs to become a `SeriesInt64`, and if that's the case, you should be able to use `SeriesNumeric.sum()` instead of the new `window_sum` implementation.

2022-02-21 09:30 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_df_fillna.py
> +import pandas as pd
we definitely can

2022-02-21 09:59 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_df_fillna.py
> +import pandas as pd
oh :crying_cat_face: gives different results, seems because of the way they sort NaNs.

2022-02-21 11:35 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_df_fillna.py
> +    [None, None, 1, None],
thanks, found a bug with this one!

2022-02-21 19:47 UTC, jansentom commented on bach/tests/functional/bach/test_df_fillna.py
> +    [None, None, 1, None],
![662fq8](https://user-images.githubusercontent.com/10804239/155017792-70f370a1-a7c2-4d85-9c63-9fe2c1bba9ad.jpg)

2022-02-21 20:27 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_df_fillna.py
> +    [None, None, 1, None],
LMAO

2022-02-21 20:55 UTC, thijs-obj reviewed
I like this PR a lot.

Seems very complete, good docstrings, tests, straightforward code, and inline comments explaining things :+1:

Do have a few comments here and there.

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +            `by` must also be a list and ``len(ascending) == len(by)``.
```suggestion
            `sort_by` must also be a list and ``len(ascending) == len(sort_by)``.
```

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +            `by` must also be a list and ``len(ascending) == len(by)``.
same for `ffill` and `bfill`

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +            sort_by is required if DataFrame has no order_by.
```suggestion
            sort_by is required if method is specified and the DataFrame has no order_by.
```

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        .. note::
I think we should have some note, either here or in some other place. That if the sort_by is not deterministic, that the resulting data in the DataFrame is then non-deterministic and 'unstable', i.e. the data of this operation might change retro-actively after doing other operations on the resulting DataFrame

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +Scalar = Optional[Union[int, float, str, UUID]]
```suggestion
Scalar = Union[int, float, str, bool, date, datetime, time, UUID]
```

This should work with date etc. too right?

I realize that my suggestion is not exhaustive either, but seems nice to have the python types for the 'basic' series at least. 
Also I realize that  `bool` is technically included already as it's a subtype of `int`, but I think it's nice to be explicit

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        :param name: Name for the savepoint. This will be the name of the table or view if that's set as
```suggestion
```

line is a duplicate of the line below it

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +            `by` must also be a list and ``len(ascending) == len(by)``.
```suggestion
            `sort_by` must also be a list and ``len(ascending) == len(sort_by)``.
```

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +            `by` must also be a list and ``len(ascending) == len(by)``.
```suggestion
            `sort_by` must also be a list and ``len(ascending) == len(sort_by)``.
```

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        # create a partition column for each series to be filled
I very much appreciate this explanation :ok_hand:

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +            raise Exception('dataframe must be sorted in order to apply forward fill.')
```suggestion
            raise Exception('dataframe must be sorted in order to apply forward or backward fill.')
````

This exception can also be indirectly triggered through `bfill()`

2022-02-21 20:55 UTC, thijs-obj commented on bach/docs/source/core_concepts.rst
> +  :py:meth:`DataFrame.sort_values()` or :py:meth:`DataFrame.fillna()` call, then the order of the rows that the data-transfer
I think we should have a more comprehensive explanation here. See also my comment above. 

`fillna()` (and `drop_duplicates()`)  are a special case of tricky. If you do `fillna()` on a DataFrame that's not deterministically sorted, and then you continue working with that frame, then even twenty operations later the data is still non-deterministic. So you might have a dataframe whose data is 'unstable' and you might never notice. You might do `head()` in between to check on the data, and you might sort the dataframe multiple times afterwards, but none of that fixes the unstable data situation. In the end all operations are compressed to one big sql query, and if somewhere at the start there is a non-deterministic part, then the whole query is non-deterministic.

Not really sure what the right words are to explain this. We could also do this as a separate issue, as the maybe the explanation should be a whole subsection in this file, but we definitely need to explain this well.


P.S. `window_row_number()`, `window_rank()`, and related functions have the same problem potential, but I imagine they are less likely to be used so that helps a bit there.

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        # bfill is similar to ffill, the difference is that the order is reversed.
nice method of doing this :ok_hand:

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        df._order_by = [
Could we use `copy_override()` here?

Generally we almost never assign anything to `df._x` but always call `df.copy_override(x=)`. This makes it a lot easier to check that we don't accidentally mutate state. For example just searching for `self._` in this file make it clear that there are only a few places where we do in-place changes, and it's easy to check all occurrences. If we have a lot of legitimate `self._x=` usage instead of `df.copy_override()` then it will be harder to audit that in the future

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        df._order_by = [
for example something like
```python
        main_order_by = df.order_by
        reverse_order_by = [
            SortColumn(expression=ob.expression, asc=not ob.asc)
            for ob in main_order_by
        ]
        return df.copy_override(sort_by=reverse_order_by).ffill().copy_override(sort_by=main_order_by)
```

2022-02-21 20:55 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        df._order_by = [
This opinion of my might be controversial with other reviewers.

2022-02-22 10:45 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        :param name: Name for the savepoint. This will be the name of the table or view if that's set as
oh wow I'm  not even sure how I added that change. Thanks!

2022-02-22 10:50 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        df._order_by = [
sounds good to me

2022-02-22 10:56 UTC, KathiaBarahona commented on bach/docs/source/core_concepts.rst
> +  :py:meth:`DataFrame.sort_values()` or :py:meth:`DataFrame.fillna()` call, then the order of the rows that the data-transfer
I think it is better to create an issue that addresses this, because to be honest I was/am not really sure how to explain it in a clear way, maybe it is one of those situations that it's better to explain through examples than words. What about creating an specific section just for this?

2022-02-22 11:01 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +            )
ohhh shoot, I should test for all dtypes

2022-02-22 11:36 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +Scalar = Optional[Union[int, float, str, UUID]]
it sorta should. I'd just copied the types supported in `const_to_series` since that's what we call on Series.fillna

2022-02-22 11:42 UTC, KathiaBarahona commented on bach/bach/dataframe.py
> +        .. note::
Will add it there. I created an issue for it as well, https://github.com/objectiv/objectiv-analytics/issues/498

2022-02-22 13:24 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        .. note::
I think we should use the `.. warning::` syntax for the warning about 'if sort_by is non-deterministic'. For an example on how that looks see https://staging.objectiv.io/docs/modeling/DataFrame/bach.DataFrame.window

Also good to do that as part of https://github.com/objectiv/objectiv-analytics/issues/498, but then we must not forget to pick up that issue soon

2022-02-23 12:54 UTC, thijs-obj commented on bach/bach/dataframe.py
> +        .. note::
Can we copy the warning to `bfill()` and `ffill()` too?

2022-02-23 12:58 UTC, thijs-obj approved these changes
two small comments. otherwise looks good to me.

2022-02-23 13:30 UTC, jansentom approved these changes
LGTM, thanks for the fixes!

2022-02-23 13:33 UTC, merged