Parallelization using pytest-xdist, engine dialect singleton
objectiv/objectiv-analytics pull request #659
Opened 2022-04-19 13:58 UTC by KathiaBarahona

Decided to use [pytest-xdist ](https://pytest-xdist.readthedocs.io/en/latest/distribution.html) since it was the most efficient one that I tried. 

Currently it uses [-n auto](https://pytest-xdist.readthedocs.io/en/latest/distribution.html#:~:text=pass%20-n%20auto%20to%20use%20as%20many%20processes%20as%20your%20computer%20has%20cpu%20cores.%20this%20can%20lead%20to%20considerable%20speed%20ups%2C%20especially%20if%20your%20test%20suite%20takes%20a%20noticeable%20amount%20of%20time.), so it creates workers based on the number of CPU cores available. 

**Results of Parallelization w/ 4 workers**
![image](https://user-images.githubusercontent.com/8259208/164022126-5b6b341d-ebcb-43e6-82b5-7387c5f3b385.png)

**Results wo/ Parallelization**
![image](https://user-images.githubusercontent.com/8259208/164024167-a1bfd5d8-a0f0-4394-9d94-f670641cf06c.png)

2022-04-19 14:41 UTC, thijs-obj commented on bach/pytest.ini
>  # -W error::DeprecationWarning: Raise an error if we encounter a DeprecationWarning
what does -nauto do?

2022-04-19 14:52 UTC, thijs-obj commented on bach/tests/conftest.py
> +        # create dialect only if we are running unit tests or db independent tests
```suggestion
        # create only dialect, if we are running unit tests or db independent tests
```

2022-04-19 14:52 UTC, thijs-obj commented on bach/tests/conftest.py
> +        # create dialect only if we are running unit tests or db independent tests
Maybe even
```suggestion
        # create only dialect, if we are running unit tests
```

As the db-independent marker just implies that it is a unit-test.

2022-04-19 14:53 UTC, thijs-obj commented on bach/tests/conftest.py
> +    # For more information, please see:
:+1:

2022-04-19 15:00 UTC, thijs-obj commented on bach/tests/conftest.py
> +        ('tests/unit' in session.config.args and len(session.config.args) == 1)
Can we not write it as this?
```suggestion
        session.config.args == ['tests/unit']
```

2022-04-19 15:12 UTC, thijs-obj requested changes
Looks very epic. _much_ faster when running all tests.

One important comment tho: `-nauto` doesn't work for me. That spins up 8 workers on my laptop. I get `sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  sorry, too many clients already` on some of the tests.
I think we should set the maximum number of connections that Postgres allows higher to solve that. For now we can also limit things to `-n4` maybe? so we can get this merged asap

2022-04-19 20:41 UTC, thijs-obj commented
One more thing, that I forgot before: not all of our tests are read-only. We should make sure that all tests that write to the DB run sequentially and/or make sure they have no race conditions. Making sure they run sequentially seems like the simplest option then?

We could mark all such tests with some decorator, or maybe use a specific fixture to mark them (e.g `engine_writable` instead of `engine`). But not sure if pytest-xdist can then make sure they run non-concurrently?

2022-04-20 18:29 UTC, jansentom commented on bach/pytest.ini
>  # -W error::DeprecationWarning: Raise an error if we encounter a DeprecationWarning
agree, multithreaded testing only on demand makes sense to me too.

2022-04-20 18:33 UTC, jansentom reviewed
Apart from comments made by Thijs, LGTM. Nice improvement that worked out of the box locally! :rocket:

2022-04-25 06:44 UTC, KathiaBarahona commented on bach/tests/conftest.py
> +        ('tests/unit' in session.config.args and len(session.config.args) == 1)
oh yes we can, duh me:)

2022-04-25 08:46 UTC, thijs-obj commented on bach/Makefile
> +	pytest -n 4 --dist loadgroup --big-query tests/unit tests/functional tests/
let's also do this on line 6

2022-04-25 08:46 UTC, thijs-obj commented on bach/tests/functional/bach/test_df_from.py
> +@pytest.mark.xdist_group(name="test_table_writers")
Question: Is it on purpose that we have a different group name here than in `test_savepoints.py`?

2022-04-25 08:52 UTC, thijs-obj approved these changes
two comments/questions. But looks good to me generally :ok_hand:

2022-04-25 09:46 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_df_from.py
> +@pytest.mark.xdist_group(name="test_table_writers")
yes, they write on different tables. So, I don't see the purpose of waiting for tests that are unrelated if they are not writing on the same table

2022-04-25 10:30 UTC, merged