Support Window Functions for BigQuery
objectiv/objectiv-analytics pull request #670
Opened 2022-04-25 06:40 UTC by KathiaBarahona

- Created `WindowFunction` enum that contains all supported window functions, this way we know which support a `window_frame_clause` based on engine. For example, all [Numbering functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/numbering_functions) for BQ, don't allow this.

- Since some functions don't allow a frame clause, needed to convert `start_boundary` param as optional in `Window` class.

2022-04-26 12:50 UTC, thijs-obj commented
Are there any functional tests that now work for BigQuery that previously didn't? Or will that come in follow-up PRs?

2022-04-26 12:52 UTC, thijs-obj reviewed
Mostly looks good to me.

@jansentom perhaps you should have a look, as you originally wrote all the Window stuff

2022-04-26 12:52 UTC, thijs-obj commented on bach/bach/utils.py
> +class WindowFunction(Enum):
There are some Windowing related enums in `partitioning.py`, any reason to not put this one there too?

2022-04-26 12:52 UTC, thijs-obj commented on bach/bach/series/series.py
> +        if not window:
Is this not sort of duplicating logic of `_check_unwrap_groupby()`? I am confused on what we check there and what exactly we check here

2022-04-26 12:52 UTC, thijs-obj commented on bach/bach/series/series.py
> +        return cast(Window, self._check_unwrap_groupby(window_cp, isin=Window))
Should we not call `_check_unwrap_groupby()` first, and then do some of the logic in this function like, removing the bounderies from the frame clause? 

e.g. above we have a check `isinstance(window_cp, Window)`, that should always be true after calling `_check_unwrap_groupby`, or at least we won't need the cast after asserting that

2022-04-26 12:52 UTC, thijs-obj commented on bach/tests/functional/bach/test_df_groupby.py
> +from bach.utils import WindowFunction
```suggestion
```

2022-04-26 13:27 UTC, jansentom requested changes
In general, LGTM, but two important things that need addressing imho

2022-04-26 13:27 UTC, jansentom commented on bach/bach/series/series.py
> +        if not window:
this method being quite complex could use some tests imho.

2022-04-26 13:39 UTC, KathiaBarahona commented on bach/bach/utils.py
> +class WindowFunction(Enum):
I was actually not really sure were to put this, I guess it's better to create a package just for partitioning and create an utils module there, for all enums and helpers

2022-04-26 13:44 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +            window_cp = window_cp.set_frame_clause(start_boundary=None, end_boundary=None)
same :/ but I had no other idea for doing. Do you have an alternative?

2022-04-26 13:45 UTC, KathiaBarahona commented on bach/bach/utils.py
> +    NAVIGATION_FUNCTIONS = (
True, will change this

2022-04-26 14:45 UTC, jansentom commented on bach/bach/series/series.py
> +        if not window:
It first gets a possible window object:
from docstring: 
        1. If `wrapped` is a GroupBy, or if it contains one, use that.
        2. If it's None, check whether this Series has a group_by set and use that.
        3. If that still yields nothing, create a GroupBy([]) and use that.
after it checks whether it actually yielded one, and that it is a true Window, not a GroupBy.

Could you not call that on the top of this method, and on the resulting window check whether there are unsupported frame clauses set? That feels way more logical, but I might be missing the point of this slightly different implementation here.

2022-04-27 09:23 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +        return cast(Window, self._check_unwrap_groupby(window_cp, isin=Window))
yeaah, I think I was testing other stuff and over complicated myself.

2022-04-27 09:24 UTC, KathiaBarahona commented on bach/bach/series/series.py
> +            window_cp = window_cp.set_frame_clause(start_boundary=None, end_boundary=None)
wdym?

2022-05-03 13:49 UTC, jansentom approved these changes
Thanks, clean improvement!

2022-05-03 14:45 UTC, merged