Bach: Support C-Standard Date Codes in `DateTimeOperation.sql_format`
objectiv/objectiv-analytics pull request #797
Opened 2022-05-30 19:57 UTC by KathiaBarahona

Since BigQuery uses standard date codes, seems it's easier for `bach` to support them by default. 
In case for PG codes, the function will try to parse the format from standard to PG, for example: `%Y-%m-%d` will be parsed into `YYYY-MM-DD`

 Still, it's possible to just use PG format by just calling `sql_format('YYYY', parse_format_str=False)`

2022-05-30 20:02 UTC, KathiaBarahona commented on bach/bach/series/utils/datetime_formats.py
> +    'LOCALE_TIME': 'HH24:MI:SS',
ofc, this depends on the locale. Not sure if we should keep this :woman_shrugging:

2022-05-31 13:02 UTC, thijs-obj requested changes
I think we are trying to do too much here. The backwards compatibility seems unnecessary to me. I suggest we add a `strftime` function, and remove the old `sql_format()` (either now or in the future). Then we don't need to have the extra parameter that indicates whether we use a database specific format string or a strftime format string.

We don't have any unittests for the translation of format strings from one format to the other, and I am sure there are edge cases that don't work[1]. Making those edge cases work doesn't have a lot of priority I believe, but having some basic unittests would be nice.


[1] Example edge case: `'%g%y'` becomes `'IYYY'`, but `to_char('IYYY')` on postgres gives a  different value than `strftime('%g%y')` on python. It seems the correct result would be `'IY""YY'`

2022-05-31 13:33 UTC, KathiaBarahona commented on bach/bach/series/series_datetime.py
> +            used without any changes.
same thing, didn't want to repeat myself. But will change since it might cause confusion

2022-05-31 13:38 UTC, KathiaBarahona commented on bach/bach/series/utils/datetime_formats.py
> +        code_name = [name for name, code in codes_to_replace.items() if code == to_repl_code][0]
I actually started with an Enum (that's why all keys are in upper case). But I think I eventually felt it was just too much for something really simple. :woman_shrugging:  Do you have another idea?

2022-05-31 14:03 UTC, hendrik-obj commented on bach/bach/series/series_datetime.py
> +    def sql_format(self, format_str: str, parse_format_str: bool = True) -> SeriesString:
maybe indeed new function will be nicer and a deprecation warning to the old one. discussed that also with Vard and Vincent. sorry, this pr is here just to quick, so I didn't mention that yet..

2022-05-31 14:23 UTC, hendrik-obj commented on bach/tests/functional/bach/test_series_date.py
> +    pd.testing.assert_frame_equal(expected, result[supported_codes].to_pandas())
could `AM_OR_PM_LOWER` somehow also depend on locale settings? I am getting `P` for expected data in the test and therefore the test fails (postgres)

2022-05-31 14:23 UTC, hendrik-obj commented on bach/tests/functional/bach/test_series_date.py
> +        non_supported_codes = [
can we inform users that they are using unsupported codes?

2022-06-02 09:29 UTC, KathiaBarahona commented on bach/bach/series/series_datetime.py
> +            Currently, this uses  1989 C standard format codes:
Done here https://github.com/objectiv/objectiv-analytics/pull/797/commits/79789748fcc902daaaa086e962702548ebea7457

2022-06-02 09:29 UTC, KathiaBarahona commented on bach/bach/series/series_datetime.py
> +    def sql_format(self, format_str: str, parse_format_str: bool = True) -> SeriesString:
Removed here https://github.com/objectiv/objectiv-analytics/pull/797/commits/79789748fcc902daaaa086e962702548ebea7457

2022-06-02 09:29 UTC, KathiaBarahona commented on bach/bach/series/utils/datetime_formats.py
> +        code_name = [name for name, code in codes_to_replace.items() if code == to_repl_code][0]
Done here: https://github.com/objectiv/objectiv-analytics/pull/797/commits/79789748fcc902daaaa086e962702548ebea7457

2022-06-02 09:29 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_date.py
> +        non_supported_codes = [
Yes, done here: https://github.com/objectiv/objectiv-analytics/pull/797/commits/79789748fcc902daaaa086e962702548ebea7457

2022-06-02 09:39 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_date.py
> +    pd.testing.assert_frame_equal(expected, result[supported_codes].to_pandas())
I removed this one

2022-06-02 10:05 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_date.py
> +    pd.testing.assert_frame_equal(expected, result[supported_codes].to_pandas())
Could you  try with this one https://github.com/objectiv/objectiv-analytics/blob/ceda97581efc56c074c77cc2d5d77ada26941177/bach/tests/functional/bach/test_series_date.py#L148-L165 (added UTC timezone, might help)

2022-06-03 08:57 UTC, KathiaBarahona commented
**BigQuery doesn't support ``%f`` Code:**

BigQuery supports most of C Code formats, but `%f` is not one of them. **Main Problem** is that ModelHub relays on seconds fractional part (microseconds/milliseconds):
https://github.com/objectiv/objectiv-analytics/blob/3f2039e51c3863f1679b7fb4fdeeddd68d7a41d3/modelhub/modelhub/modelhub.py#L23

Now, for example:

```python
from datetime import datetime
dt = datetime(2022, 6, 3, 9, 53, 30, 123456)

print(dt.strftime("%Y-%m-%d %H:%M:%S.%f"))
#  >> 2022-06-03 09:53:30.123456
```

Will actually yield  `2022-06-03 09:53:30.%f` in BigQuery, now if you want the format to work in BigQuery, you should use:
`%Y-%m-%d %H:%M:%E6S` (`E6S` include seconds with 6 digits of fractional precision).

Example:
```sql
SELECT 
FORMAT_DATE('%Y-%m-%d %H:%M:%S.%f', CURRENT_DATETIME()) as incorrect_format_microseconds,
FORMAT_DATE('%Y-%m-%d %H:%M:%E6S', CURRENT_DATETIME()) as correct_format_microseconds, 
FORMAT_DATE('%Y-%m-%d %H:%M:%E3S', CURRENT_DATETIME()) as correct_format_milliseconds
```

So, I have a couple of questions:
1. How should we treat this? Just replacing `%S.%f` with `%E6S` might solve the problem, but still if user just wants microseconds? Do we just ignore this case and show `%f`? (Not sure if is worth to raise a warning, or maybe yes..?)

2. There's not code for milliseconds, but we currently use them in ModelHub default format
      If we currently want Bach, to generate that: 
              for Postgres: `time_series.dt.strftime("'%Y-%m-%d %H:%M:%S.MS)`
              for BigQuery: `time_series.dt.strftime("'%Y-%m-%d %H:%M:%E3S")`
     which is a bit nasty.
     So, should we create a new code for milliseconds? or just use microseconds?


**Conclusion**
After discussing with @jansentom 
1. replacing `%S.%f` with `%E6S`, and throwing exception/user warning if we encounter a `%f` after that.
2. Modelhub should use microseconds instead.

2022-06-03 09:58 UTC, thijs-obj reviewed
Just committing my review, so my previous review won't block merging after this is reviewed. Didn't review again, but don't think all changes are here either?

2022-06-03 09:59 UTC, thijs-obj approved these changes
ow, so that didn't actually work. I'll approve then just to please github. But as I said before, I haven't actually reviewed it again after what we discussed yesterday.

2022-06-03 10:00 UTC, KathiaBarahona commented
> Just committing my review, so my previous review won't block merging after this is reviewed. Didn't review again, but don't think all changes are here either?

I'm just missing the substitution of `%S.%f` for BigQuery and removing `%p` code to avoid issues with locale. Thanks for unblocking!

2022-06-03 10:02 UTC, thijs-obj commented on bach/bach/series/utils/datetime_formats.py
> +        Step 1: Get all unique groups of continuous c-codes,
Would a while loop that runs over all characters not simpler? Keep a result string, and just keep adding characters to that, when running into a code look that up in the dictionary

2022-06-03 10:13 UTC, KathiaBarahona commented on bach/bach/series/utils/datetime_formats.py
> +        Step 1: Get all unique groups of continuous c-codes,
Yes, but I think it returns a kinda ugly string or maybe something I wouldn't write when doing the query manually. For example:
`%Y-%m-%d` will return: `YYYY""-MM""-DD""` instead of `YYYY-MM-DD`. Since by just keep adding characters to the result string we are not aware when we already parsed a code.

2022-06-03 15:19 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_date.py
> +    pd.testing.assert_frame_equal(expected, result[supported_codes].to_pandas())
Removed that code in https://github.com/objectiv/objectiv-analytics/pull/797/commits/f17680f8cac2f65f440cdd1437dd002eb765162b

2022-06-07 15:42 UTC, thijs-obj approved these changes
Left some questions/comments.

At some point we need to move on from this tho. So I am also fine with merging this as is. it's all very contained.

2022-06-07 15:42 UTC, thijs-obj commented on bach/tests/functional/bach/test_series_date.py
> +        percentage_format_date = '2022-%%01-01'  # %% is not supported for pg
can we not just add `"%%": "%"` to `_C_STANDARD_CODES_X_POSTGRES_DATE_CODES`?

2022-06-07 15:42 UTC, thijs-obj commented on bach/bach/series/utils/datetime_formats.py
> +    grouped_codes_matches = re.findall(pattern=rf"(?P<codes>({codes_base_pattern})+)", string=date_format)
```suggestion
    grouped_codes_matches = re.findall(pattern=rf"(?P<codes>(?:{codes_base_pattern})+)", string=date_format)
```
Then we only get a single group from the regex. and we don't need to discard the second one (line 137 and 140)

2022-06-07 15:42 UTC, thijs-obj commented on bach/bach/series/utils/datetime_formats.py
> +    if '%S.%f' in date_format:
There are probably some edge cases here, like `%%S.%f`. but that's not a really big deal I think

2022-06-07 15:42 UTC, thijs-obj commented on bach/tests/unit/bach/test_series_utils_datetime_formats.py
> +    assert parse_c_standard_code_to_postgres_code('YYYYMMDD') == '"YYYYMMDD"'
:+1:

2022-06-08 05:29 UTC, KathiaBarahona commented on bach/bach/series/utils/datetime_formats.py
> +    grouped_codes_matches = re.findall(pattern=rf"(?P<codes>({codes_base_pattern})+)", string=date_format)
hah worked! Thanks!

2022-06-08 05:46 UTC, merged