Bach BQ: SeriesJson slicing with dicts
objectiv/objectiv-analytics pull request #852
Opened 2022-06-08 14:49 UTC by KathiaBarahona

Followed this approach: https://docs.google.com/document/d/1yPt4ML5liYgqiRbbJmhW_j3Co5PkSA0539nKocb25xg

2022-06-08 15:13 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_json.py
> +def test_json_same_start_end_slicing(engine, dtype):
https://github.com/objectiv/objectiv-analytics/issues/853

2022-06-08 19:49 UTC, jansentom commented on bach/bach/series/series_json.py
> +        # this way we can reuse code from the accesor without duplicating
I was a bit confused about what `element` mean, until I discovered it in the query template below. Maybe this helps for others suffering from local blindness :)

```suggestion
        # this way we can reuse code from the accesor without duplicating.
        # 'element' will filled by iterating over the json array in the query below.
```

2022-06-08 19:51 UTC, jansentom commented on bach/tests/functional/bach/test_series_json.py
> +def test_json_same_start_end_slicing(engine, dtype):
Hmm, does @hendrik-obj rely on this behaviour?

2022-06-08 19:54 UTC, jansentom commented on bach/tests/functional/bach/test_series_json.py
> +def test_json_same_start_end_slicing(engine, dtype):
The pydoc in the accessor also states the "broken" behaviour if I understand you correctly. Should we follow `.loc` behaviour here or invent our own? WDYT?

2022-06-08 19:57 UTC, jansentom reviewed
Very simple solution actually and useful to have! Let's check what to do with in/exclusive end of slice behaviour. @hendrik-obj @vard-obj Please shine your light as well, thanks!

2022-06-08 19:59 UTC, thijs-obj approved these changes
lgtm

I do think that we should not 'abuse' the slice operation for this. Don't think mypy likes that either. But that's a separate issue that we need to discuss with everyone involved.

2022-06-08 19:59 UTC, thijs-obj commented on bach/bach/series/series_json.py
> +        # this way we can reuse code from the accesor without duplicating
clever

2022-06-09 06:36 UTC, KathiaBarahona commented on bach/bach/series/series_json.py
> +        # this way we can reuse code from the accesor without duplicating
Done in https://github.com/objectiv/objectiv-analytics/pull/852/commits/10397788d40f0ef62c196d0f1bf6e8e049624847

2022-06-09 06:41 UTC, KathiaBarahona commented on bach/tests/functional/bach/test_series_json.py
> +def test_json_same_start_end_slicing(engine, dtype):
Mmmm if you added the correct pydoc, it seems that's a seperate issue. Regards, the inclusive issue.. seems that modelhub uses only dicts for start slice, which I only found in tests and here https://github.com/objectiv/objectiv-analytics/blob/4a6cd2479387512cf52fc89630b56bb54da9e228/modelhub/modelhub/series/series_objectiv.py#L171

2022-06-13 14:13 UTC, hendrik-obj commented on bach/tests/functional/bach/test_series_json.py
> +def test_json_same_start_end_slicing(engine, dtype):
sorry for late to this party. 
Yes, the inspiration for doing it as it was (including the value) was that it is the same as `.loc`. 
Another reason (or maybe the reason for the loc implementation) is that it is in many cases, easier. For example, it is easy to get from the slice that includes the matching end-dict, to the matching dict minus the last object. The other way around however, is difficult.

2022-06-13 14:14 UTC, hendrik-obj commented on bach/tests/functional/bach/test_series_json.py
> +def test_json_same_start_end_slicing(engine, dtype):
So, it is not 'broken' as https://github.com/objectiv/objectiv-analytics/issues/853 suggests.

2022-06-13 14:16 UTC, hendrik-obj requested changes
imo we should keep the postgres behaviour. see comments.

2022-06-13 14:16 UTC, hendrik-obj commented on bach/bach/series/series_json.py
> +            f"(select {'min' if is_start else 'max'}(case when {{}} then pos end) "
```suggestion
            f"(select {'min' if is_start else '1 + max'}(case when {{}} then pos end) "
```
not fully tested, but something like this gives the expected `.loc`-like behaviour

2022-06-13 15:12 UTC, thijs-obj commented on bach/tests/functional/bach/test_series_json.py
> +def test_json_same_start_end_slicing(engine, dtype):
I don't know `.loc` well. How does that handle 'normal' slices with integers? Does that handle it in the same way we do, or should we change that too?

2022-06-13 15:45 UTC, hendrik-obj commented on bach/tests/functional/bach/test_series_json.py
> +def test_json_same_start_end_slicing(engine, dtype):
But seeing the discussion, there might be something that is more clear for everybody? finding the position of a matching object in an array as a separate function for example? downside is that the syntax will get quite big if you then want to do a slices.

2022-06-13 18:51 UTC, hendrik-obj commented
this test should pass in this pr for bq now: `test_objectiv_stack_type3` in `test_series_objectiv.py`. good to keep track of this somehow.

2022-06-14 06:30 UTC, merged